/* Generated by Yosys 0.54 (git sha1 db72ec3bd, g++ 15.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) */

module apb_i2c(HCLK, HRESETn, PADDR, PWDATA, PWRITE, PSEL, PENABLE, PRDATA, PREADY, PSLVERR, interrupt_o, scl_pad_i, scl_pad_o, scl_padoen_o, sda_pad_i, sda_pad_o, sda_padoen_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire [7:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  input HCLK;
  wire HCLK;
  input HRESETn;
  wire HRESETn;
  input [11:0] PADDR;
  wire [11:0] PADDR;
  input PENABLE;
  wire PENABLE;
  output [31:0] PRDATA;
  wire [31:0] PRDATA;
  output PREADY;
  wire PREADY;
  input PSEL;
  wire PSEL;
  output PSLVERR;
  wire PSLVERR;
  input [31:0] PWDATA;
  wire [31:0] PWDATA;
  input PWRITE;
  wire PWRITE;
  wire ack;
  wire al;
  wire i2c_al;
  wire i2c_busy;
  wire iack;
  output interrupt_o;
  wire interrupt_o;
  wire irq_flag;
  wire [7:0] r_cmd;
  wire [7:0] r_ctrl;
  wire [15:0] r_pre;
  wire [7:0] r_tx;
  wire rd;
  wire rxack;
  wire [3:0] s_apb_addr;
  wire s_core_en;
  wire s_done;
  wire s_ien;
  wire s_irxack;
  wire [7:0] s_rx;
  wire [7:0] s_status;
  input scl_pad_i;
  wire scl_pad_i;
  output scl_pad_o;
  wire scl_pad_o;
  output scl_padoen_o;
  wire scl_padoen_o;
  input sda_pad_i;
  wire sda_pad_i;
  output sda_pad_o;
  wire sda_pad_o;
  output sda_padoen_o;
  wire sda_padoen_o;
  wire sta;
  wire sto;
  wire tip;
  wire wr;
  sky130_fd_sc_hd__clkinv_1 _349_ (
    .A(_183_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__clkinv_1 _350_ (
    .A(_184_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__clkinv_1 _351_ (
    .A(_185_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__clkinv_1 _352_ (
    .A(_272_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__and2_0 _353_ (
    .A(_279_),
    .B(_226_),
    .X(_141_)
  );
  sky130_fd_sc_hd__nor4bb_1 _354_ (
    .A(_152_),
    .B(_154_),
    .C_N(_153_),
    .D_N(_151_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__and3_1 _355_ (
    .A(_155_),
    .B(_172_),
    .C(_189_),
    .X(_232_)
  );
  sky130_fd_sc_hd__and3_1 _356_ (
    .A(_280_),
    .B(_231_),
    .C(_232_),
    .X(_233_)
  );
  sky130_fd_sc_hd__nor2_1 _357_ (
    .A(_224_),
    .B(_306_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nand2_1 _358_ (
    .A(_269_),
    .B(_234_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__mux2i_1 _359_ (
    .A0(_235_),
    .A1(_227_),
    .S(_233_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _360_ (
    .A(_270_),
    .B(_234_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__mux2i_1 _361_ (
    .A0(_236_),
    .A1(_228_),
    .S(_233_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _362_ (
    .A(_271_),
    .B(_234_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__mux2i_1 _363_ (
    .A0(_237_),
    .A1(_229_),
    .S(_233_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor3_1 _364_ (
    .A(_224_),
    .B(_306_),
    .C(_230_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__mux2_1 _365_ (
    .A0(_238_),
    .A1(_186_),
    .S(_233_),
    .X(_149_)
  );
  sky130_fd_sc_hd__and2_0 _366_ (
    .A(_180_),
    .B(_233_),
    .X(_144_)
  );
  sky130_fd_sc_hd__and2_0 _367_ (
    .A(_181_),
    .B(_233_),
    .X(_145_)
  );
  sky130_fd_sc_hd__nor4b_1 _368_ (
    .A(_152_),
    .B(_151_),
    .C(_154_),
    .D_N(_153_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nor4_1 _369_ (
    .A(_152_),
    .B(_151_),
    .C(_154_),
    .D(_153_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__nor4b_1 _370_ (
    .A(_152_),
    .B(_154_),
    .C(_153_),
    .D_N(_151_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nand2_1 _371_ (
    .A(_273_),
    .B(_241_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nor4b_1 _372_ (
    .A(_151_),
    .B(_154_),
    .C(_153_),
    .D_N(_152_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nor4bb_1 _373_ (
    .A(_154_),
    .B(_153_),
    .C_N(_152_),
    .D_N(_151_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__a22oi_1 _374_ (
    .A1(_281_),
    .A2(_240_),
    .B1(_243_),
    .B2(_307_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__a222oi_1 _375_ (
    .A1(_265_),
    .A2(_231_),
    .B1(_239_),
    .B2(_297_),
    .C1(_244_),
    .C2(_226_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nand3_1 _376_ (
    .A(_242_),
    .B(_245_),
    .C(_246_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a222oi_1 _377_ (
    .A1(_288_),
    .A2(_240_),
    .B1(_241_),
    .B2(_274_),
    .C1(_315_),
    .C2(_244_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__a222oi_1 _378_ (
    .A1(_266_),
    .A2(_231_),
    .B1(_239_),
    .B2(_298_),
    .C1(_243_),
    .C2(_308_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nand2_1 _379_ (
    .A(_247_),
    .B(_248_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a22oi_1 _380_ (
    .A1(_299_),
    .A2(_239_),
    .B1(_240_),
    .B2(_289_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__a222oi_1 _381_ (
    .A1(_267_),
    .A2(_231_),
    .B1(_241_),
    .B2(_275_),
    .C1(_243_),
    .C2(_309_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nand2_1 _382_ (
    .A(_249_),
    .B(_250_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a22oi_1 _383_ (
    .A1(_300_),
    .A2(_239_),
    .B1(_240_),
    .B2(_290_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__a222oi_1 _384_ (
    .A1(_268_),
    .A2(_231_),
    .B1(_241_),
    .B2(_276_),
    .C1(_243_),
    .C2(_310_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nand2_1 _385_ (
    .A(_251_),
    .B(_252_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a22oi_1 _386_ (
    .A1(_301_),
    .A2(_239_),
    .B1(_240_),
    .B2(_291_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__a222oi_1 _387_ (
    .A1(_269_),
    .A2(_231_),
    .B1(_241_),
    .B2(_277_),
    .C1(_243_),
    .C2(_311_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__nand2_1 _388_ (
    .A(_253_),
    .B(_254_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a222oi_1 _389_ (
    .A1(_292_),
    .A2(_240_),
    .B1(_241_),
    .B2(_278_),
    .C1(_312_),
    .C2(_243_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__a222oi_1 _390_ (
    .A1(_270_),
    .A2(_231_),
    .B1(_239_),
    .B2(_302_),
    .C1(_244_),
    .C2(_190_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nand2_1 _391_ (
    .A(_255_),
    .B(_256_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__a222oi_1 _392_ (
    .A1(_279_),
    .A2(_241_),
    .B1(_244_),
    .B2(_225_),
    .C1(_293_),
    .C2(_240_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__a222oi_1 _393_ (
    .A1(_271_),
    .A2(_231_),
    .B1(_239_),
    .B2(_303_),
    .C1(_243_),
    .C2(_313_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nand2_1 _394_ (
    .A(_257_),
    .B(_258_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__a222oi_1 _395_ (
    .A1(_280_),
    .A2(_241_),
    .B1(_244_),
    .B2(_305_),
    .C1(_294_),
    .C2(_240_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__a222oi_1 _396_ (
    .A1(_272_),
    .A2(_231_),
    .B1(_239_),
    .B2(_304_),
    .C1(_243_),
    .C2(_314_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nand2_1 _397_ (
    .A(_259_),
    .B(_260_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__and2_0 _398_ (
    .A(_295_),
    .B(_240_),
    .X(_170_)
  );
  sky130_fd_sc_hd__and2_0 _399_ (
    .A(_296_),
    .B(_240_),
    .X(_171_)
  );
  sky130_fd_sc_hd__and2_0 _400_ (
    .A(_282_),
    .B(_240_),
    .X(_157_)
  );
  sky130_fd_sc_hd__and2_0 _401_ (
    .A(_283_),
    .B(_240_),
    .X(_158_)
  );
  sky130_fd_sc_hd__and2_0 _402_ (
    .A(_284_),
    .B(_240_),
    .X(_159_)
  );
  sky130_fd_sc_hd__and2_0 _403_ (
    .A(_285_),
    .B(_240_),
    .X(_160_)
  );
  sky130_fd_sc_hd__and2_0 _404_ (
    .A(_286_),
    .B(_240_),
    .X(_161_)
  );
  sky130_fd_sc_hd__and2_0 _405_ (
    .A(_287_),
    .B(_240_),
    .X(_162_)
  );
  sky130_fd_sc_hd__a21o_1 _406_ (
    .A1(_230_),
    .A2(_190_),
    .B1(_224_),
    .X(_140_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _407_ (
    .A(_269_),
    .SLEEP(_270_),
    .X(_150_)
  );
  sky130_fd_sc_hd__nor3_1 _408_ (
    .A(_226_),
    .B(_224_),
    .C(_306_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nor2_1 _409_ (
    .A(_265_),
    .B(_261_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__and2_0 _410_ (
    .A(_173_),
    .B(_233_),
    .X(_143_)
  );
  sky130_fd_sc_hd__mux2_1 _411_ (
    .A0(_268_),
    .A1(_182_),
    .S(_233_),
    .X(_191_)
  );
  sky130_fd_sc_hd__and2_0 _412_ (
    .A(_232_),
    .B(_240_),
    .X(_262_)
  );
  sky130_fd_sc_hd__mux2_1 _413_ (
    .A0(_281_),
    .A1(_173_),
    .S(_262_),
    .X(_192_)
  );
  sky130_fd_sc_hd__mux2_1 _414_ (
    .A0(_288_),
    .A1(_180_),
    .S(_262_),
    .X(_193_)
  );
  sky130_fd_sc_hd__mux2_1 _415_ (
    .A0(_289_),
    .A1(_181_),
    .S(_262_),
    .X(_194_)
  );
  sky130_fd_sc_hd__mux2_1 _416_ (
    .A0(_290_),
    .A1(_182_),
    .S(_262_),
    .X(_195_)
  );
  sky130_fd_sc_hd__mux2_1 _417_ (
    .A0(_291_),
    .A1(_183_),
    .S(_262_),
    .X(_196_)
  );
  sky130_fd_sc_hd__mux2_1 _418_ (
    .A0(_292_),
    .A1(_184_),
    .S(_262_),
    .X(_197_)
  );
  sky130_fd_sc_hd__mux2_1 _419_ (
    .A0(_293_),
    .A1(_185_),
    .S(_262_),
    .X(_198_)
  );
  sky130_fd_sc_hd__mux2_1 _420_ (
    .A0(_294_),
    .A1(_186_),
    .S(_262_),
    .X(_199_)
  );
  sky130_fd_sc_hd__mux2_1 _421_ (
    .A0(_295_),
    .A1(_187_),
    .S(_262_),
    .X(_200_)
  );
  sky130_fd_sc_hd__mux2_1 _422_ (
    .A0(_296_),
    .A1(_188_),
    .S(_262_),
    .X(_201_)
  );
  sky130_fd_sc_hd__mux2_1 _423_ (
    .A0(_282_),
    .A1(_174_),
    .S(_262_),
    .X(_202_)
  );
  sky130_fd_sc_hd__mux2_1 _424_ (
    .A0(_283_),
    .A1(_175_),
    .S(_262_),
    .X(_203_)
  );
  sky130_fd_sc_hd__mux2_1 _425_ (
    .A0(_284_),
    .A1(_176_),
    .S(_262_),
    .X(_204_)
  );
  sky130_fd_sc_hd__mux2_1 _426_ (
    .A0(_285_),
    .A1(_177_),
    .S(_262_),
    .X(_205_)
  );
  sky130_fd_sc_hd__mux2_1 _427_ (
    .A0(_286_),
    .A1(_178_),
    .S(_262_),
    .X(_206_)
  );
  sky130_fd_sc_hd__mux2_1 _428_ (
    .A0(_287_),
    .A1(_179_),
    .S(_262_),
    .X(_207_)
  );
  sky130_fd_sc_hd__and2_0 _429_ (
    .A(_232_),
    .B(_241_),
    .X(_263_)
  );
  sky130_fd_sc_hd__mux2_1 _430_ (
    .A0(_273_),
    .A1(_173_),
    .S(_263_),
    .X(_208_)
  );
  sky130_fd_sc_hd__mux2_1 _431_ (
    .A0(_274_),
    .A1(_180_),
    .S(_263_),
    .X(_209_)
  );
  sky130_fd_sc_hd__mux2_1 _432_ (
    .A0(_275_),
    .A1(_181_),
    .S(_263_),
    .X(_210_)
  );
  sky130_fd_sc_hd__mux2_1 _433_ (
    .A0(_276_),
    .A1(_182_),
    .S(_263_),
    .X(_211_)
  );
  sky130_fd_sc_hd__mux2_1 _434_ (
    .A0(_277_),
    .A1(_183_),
    .S(_263_),
    .X(_212_)
  );
  sky130_fd_sc_hd__mux2_1 _435_ (
    .A0(_278_),
    .A1(_184_),
    .S(_263_),
    .X(_213_)
  );
  sky130_fd_sc_hd__mux2_1 _436_ (
    .A0(_279_),
    .A1(_185_),
    .S(_263_),
    .X(_214_)
  );
  sky130_fd_sc_hd__mux2_1 _437_ (
    .A0(_280_),
    .A1(_186_),
    .S(_263_),
    .X(_215_)
  );
  sky130_fd_sc_hd__and2_0 _438_ (
    .A(_232_),
    .B(_239_),
    .X(_264_)
  );
  sky130_fd_sc_hd__mux2_1 _439_ (
    .A0(_297_),
    .A1(_173_),
    .S(_264_),
    .X(_216_)
  );
  sky130_fd_sc_hd__mux2_1 _440_ (
    .A0(_298_),
    .A1(_180_),
    .S(_264_),
    .X(_217_)
  );
  sky130_fd_sc_hd__mux2_1 _441_ (
    .A0(_299_),
    .A1(_181_),
    .S(_264_),
    .X(_218_)
  );
  sky130_fd_sc_hd__mux2_1 _442_ (
    .A0(_300_),
    .A1(_182_),
    .S(_264_),
    .X(_219_)
  );
  sky130_fd_sc_hd__mux2_1 _443_ (
    .A0(_301_),
    .A1(_183_),
    .S(_264_),
    .X(_220_)
  );
  sky130_fd_sc_hd__mux2_1 _444_ (
    .A0(_302_),
    .A1(_184_),
    .S(_264_),
    .X(_221_)
  );
  sky130_fd_sc_hd__mux2_1 _445_ (
    .A0(_303_),
    .A1(_185_),
    .S(_264_),
    .X(_222_)
  );
  sky130_fd_sc_hd__mux2_1 _446_ (
    .A0(_304_),
    .A1(_186_),
    .S(_264_),
    .X(_223_)
  );
  sky130_fd_sc_hd__dfrtp_1 _447_ (
    .CLK(HCLK),
    .D(_316_),
    .Q(r_cmd[3]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _448_ (
    .CLK(HCLK),
    .D(_003_[0]),
    .Q(r_cmd[0]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _449_ (
    .CLK(HCLK),
    .D(_003_[1]),
    .Q(r_cmd[1]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _450_ (
    .CLK(HCLK),
    .D(_003_[2]),
    .Q(r_cmd[2]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _451_ (
    .CLK(HCLK),
    .D(_003_[4]),
    .Q(r_cmd[4]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _452_ (
    .CLK(HCLK),
    .D(_003_[5]),
    .Q(r_cmd[5]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _453_ (
    .CLK(HCLK),
    .D(_003_[6]),
    .Q(r_cmd[6]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _454_ (
    .CLK(HCLK),
    .D(_003_[7]),
    .Q(r_cmd[7]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _455_ (
    .CLK(HCLK),
    .D(_001_),
    .Q(interrupt_o),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _456_ (
    .CLK(HCLK),
    .D(s_irxack),
    .Q(rxack),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _457_ (
    .CLK(HCLK),
    .D(_004_),
    .Q(tip),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _458_ (
    .CLK(HCLK),
    .D(_002_),
    .Q(irq_flag),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _459_ (
    .CLK(HCLK),
    .D(_000_),
    .Q(al),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _460_ (
    .CLK(HCLK),
    .D(_317_),
    .Q(r_pre[0]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _461_ (
    .CLK(HCLK),
    .D(_318_),
    .Q(r_pre[1]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _462_ (
    .CLK(HCLK),
    .D(_319_),
    .Q(r_pre[2]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _463_ (
    .CLK(HCLK),
    .D(_320_),
    .Q(r_pre[3]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _464_ (
    .CLK(HCLK),
    .D(_321_),
    .Q(r_pre[4]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _465_ (
    .CLK(HCLK),
    .D(_322_),
    .Q(r_pre[5]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _466_ (
    .CLK(HCLK),
    .D(_323_),
    .Q(r_pre[6]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _467_ (
    .CLK(HCLK),
    .D(_324_),
    .Q(r_pre[7]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _468_ (
    .CLK(HCLK),
    .D(_325_),
    .Q(r_pre[8]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _469_ (
    .CLK(HCLK),
    .D(_326_),
    .Q(r_pre[9]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _470_ (
    .CLK(HCLK),
    .D(_327_),
    .Q(r_pre[10]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _471_ (
    .CLK(HCLK),
    .D(_328_),
    .Q(r_pre[11]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _472_ (
    .CLK(HCLK),
    .D(_329_),
    .Q(r_pre[12]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _473_ (
    .CLK(HCLK),
    .D(_330_),
    .Q(r_pre[13]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _474_ (
    .CLK(HCLK),
    .D(_331_),
    .Q(r_pre[14]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _475_ (
    .CLK(HCLK),
    .D(_332_),
    .Q(r_pre[15]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _476_ (
    .CLK(HCLK),
    .D(_333_),
    .Q(r_ctrl[0]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _477_ (
    .CLK(HCLK),
    .D(_334_),
    .Q(r_ctrl[1]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _478_ (
    .CLK(HCLK),
    .D(_335_),
    .Q(r_ctrl[2]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _479_ (
    .CLK(HCLK),
    .D(_336_),
    .Q(r_ctrl[3]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _480_ (
    .CLK(HCLK),
    .D(_337_),
    .Q(r_ctrl[4]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _481_ (
    .CLK(HCLK),
    .D(_338_),
    .Q(r_ctrl[5]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _482_ (
    .CLK(HCLK),
    .D(_339_),
    .Q(r_ctrl[6]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _483_ (
    .CLK(HCLK),
    .D(_340_),
    .Q(r_ctrl[7]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _484_ (
    .CLK(HCLK),
    .D(_341_),
    .Q(r_tx[0]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _485_ (
    .CLK(HCLK),
    .D(_342_),
    .Q(r_tx[1]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _486_ (
    .CLK(HCLK),
    .D(_343_),
    .Q(r_tx[2]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _487_ (
    .CLK(HCLK),
    .D(_344_),
    .Q(r_tx[3]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _488_ (
    .CLK(HCLK),
    .D(_345_),
    .Q(r_tx[4]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _489_ (
    .CLK(HCLK),
    .D(_346_),
    .Q(r_tx[5]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _490_ (
    .CLK(HCLK),
    .D(_347_),
    .Q(r_tx[6]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _491_ (
    .CLK(HCLK),
    .D(_348_),
    .Q(r_tx[7]),
    .RESET_B(HRESETn)
  );
  i2c_master_byte_ctrl byte_controller (
    .ack_in(r_cmd[3]),
    .ack_out(s_irxack),
    .clk(HCLK),
    .clk_cnt(r_pre),
    .cmd_ack(s_done),
    .din(r_tx),
    .dout(s_rx),
    .ena(r_ctrl[7]),
    .i2c_al(i2c_al),
    .i2c_busy(i2c_busy),
    .nReset(HRESETn),
    .read(r_cmd[5]),
    .scl_i(scl_pad_i),
    .scl_o(scl_pad_o),
    .scl_oen(scl_padoen_o),
    .sda_i(sda_pad_i),
    .sda_o(sda_pad_o),
    .sda_oen(sda_padoen_o),
    .start(r_cmd[7]),
    .stop(r_cmd[6]),
    .write(r_cmd[4])
  );
  assign PRDATA[31:16] = 16'h0000;
  assign PREADY = 1'h1;
  assign PSLVERR = 1'h0;
  assign ack = r_cmd[3];
  assign iack = r_cmd[0];
  assign rd = r_cmd[5];
  assign s_apb_addr = PADDR[5:2];
  assign s_core_en = r_ctrl[7];
  assign s_ien = r_ctrl[6];
  assign s_status = { rxack, i2c_busy, al, 3'h0, tip, irq_flag };
  assign sta = r_cmd[7];
  assign sto = r_cmd[6];
  assign wr = r_cmd[4];
  assign _155_ = PENABLE;
  assign _172_ = PSEL;
  assign _189_ = PWRITE;
  assign _280_ = r_ctrl[7];
  assign _152_ = PADDR[3];
  assign _151_ = PADDR[2];
  assign _154_ = PADDR[5];
  assign _153_ = PADDR[4];
  assign _279_ = r_ctrl[6];
  assign _226_ = irq_flag;
  assign _001_ = _141_;
  assign _224_ = i2c_al;
  assign _306_ = s_done;
  assign _269_ = r_cmd[4];
  assign _183_ = PWDATA[4];
  assign _003_[4] = _146_;
  assign _270_ = r_cmd[5];
  assign _184_ = PWDATA[5];
  assign _003_[5] = _147_;
  assign _271_ = r_cmd[6];
  assign _185_ = PWDATA[6];
  assign _003_[6] = _148_;
  assign _272_ = r_cmd[7];
  assign _186_ = PWDATA[7];
  assign _003_[7] = _149_;
  assign _180_ = PWDATA[1];
  assign _003_[1] = _144_;
  assign _181_ = PWDATA[2];
  assign _003_[2] = _145_;
  assign _265_ = r_cmd[0];
  assign _297_ = r_tx[0];
  assign _307_ = s_rx[0];
  assign _273_ = r_ctrl[0];
  assign _281_ = r_pre[0];
  assign PRDATA[0] = _156_;
  assign _266_ = r_cmd[1];
  assign _298_ = r_tx[1];
  assign _315_ = tip;
  assign _308_ = s_rx[1];
  assign _274_ = r_ctrl[1];
  assign _288_ = r_pre[1];
  assign PRDATA[1] = _163_;
  assign _267_ = r_cmd[2];
  assign _299_ = r_tx[2];
  assign _309_ = s_rx[2];
  assign _275_ = r_ctrl[2];
  assign _289_ = r_pre[2];
  assign PRDATA[2] = _164_;
  assign _268_ = r_cmd[3];
  assign _300_ = r_tx[3];
  assign _310_ = s_rx[3];
  assign _276_ = r_ctrl[3];
  assign _290_ = r_pre[3];
  assign PRDATA[3] = _165_;
  assign _301_ = r_tx[4];
  assign _311_ = s_rx[4];
  assign _277_ = r_ctrl[4];
  assign _291_ = r_pre[4];
  assign PRDATA[4] = _166_;
  assign _302_ = r_tx[5];
  assign _190_ = al;
  assign _312_ = s_rx[5];
  assign _278_ = r_ctrl[5];
  assign _292_ = r_pre[5];
  assign PRDATA[5] = _167_;
  assign _303_ = r_tx[6];
  assign _225_ = i2c_busy;
  assign _313_ = s_rx[6];
  assign _293_ = r_pre[6];
  assign PRDATA[6] = _168_;
  assign _304_ = r_tx[7];
  assign _305_ = rxack;
  assign _314_ = s_rx[7];
  assign _294_ = r_pre[7];
  assign PRDATA[7] = _169_;
  assign _295_ = r_pre[8];
  assign PRDATA[8] = _170_;
  assign _296_ = r_pre[9];
  assign PRDATA[9] = _171_;
  assign _282_ = r_pre[10];
  assign PRDATA[10] = _157_;
  assign _283_ = r_pre[11];
  assign PRDATA[11] = _158_;
  assign _284_ = r_pre[12];
  assign PRDATA[12] = _159_;
  assign _285_ = r_pre[13];
  assign PRDATA[13] = _160_;
  assign _286_ = r_pre[14];
  assign PRDATA[14] = _161_;
  assign _287_ = r_pre[15];
  assign PRDATA[15] = _162_;
  assign _000_ = _140_;
  assign _004_ = _150_;
  assign _002_ = _142_;
  assign _173_ = PWDATA[0];
  assign _003_[0] = _143_;
  assign _182_ = PWDATA[3];
  assign _316_ = _191_;
  assign _317_ = _192_;
  assign _318_ = _193_;
  assign _319_ = _194_;
  assign _320_ = _195_;
  assign _321_ = _196_;
  assign _322_ = _197_;
  assign _323_ = _198_;
  assign _324_ = _199_;
  assign _187_ = PWDATA[8];
  assign _325_ = _200_;
  assign _188_ = PWDATA[9];
  assign _326_ = _201_;
  assign _174_ = PWDATA[10];
  assign _327_ = _202_;
  assign _175_ = PWDATA[11];
  assign _328_ = _203_;
  assign _176_ = PWDATA[12];
  assign _329_ = _204_;
  assign _177_ = PWDATA[13];
  assign _330_ = _205_;
  assign _178_ = PWDATA[14];
  assign _331_ = _206_;
  assign _179_ = PWDATA[15];
  assign _332_ = _207_;
  assign _333_ = _208_;
  assign _334_ = _209_;
  assign _335_ = _210_;
  assign _336_ = _211_;
  assign _337_ = _212_;
  assign _338_ = _213_;
  assign _339_ = _214_;
  assign _340_ = _215_;
  assign _341_ = _216_;
  assign _342_ = _217_;
  assign _343_ = _218_;
  assign _344_ = _219_;
  assign _345_ = _220_;
  assign _346_ = _221_;
  assign _347_ = _222_;
  assign _348_ = _223_;
endmodule

module i2c_master_bit_ctrl(clk, nReset, ena, clk_cnt, cmd, cmd_ack, busy, al, din, dout, scl_i, scl_o, scl_oen, sda_i, sda_o, sda_oen);
  wire _0000_;
  wire _0001_;
  wire [17:0] _0002_;
  wire _0003_;
  wire _0004_;
  wire [15:0] _0005_;
  wire [13:0] _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  wire _0757_;
  wire _0758_;
  wire _0759_;
  wire [15:0] _0760_;
  output al;
  wire al;
  output busy;
  wire busy;
  wire [1:0] cSCL;
  wire [1:0] cSDA;
  wire [17:0] c_state;
  input clk;
  wire clk;
  input [15:0] clk_cnt;
  wire [15:0] clk_cnt;
  wire clk_en;
  input [3:0] cmd;
  wire [3:0] cmd;
  output cmd_ack;
  wire cmd_ack;
  wire cmd_stop;
  wire [15:0] cnt;
  wire dSCL;
  wire dSDA;
  input din;
  wire din;
  output dout;
  wire dout;
  wire dscl_oen;
  input ena;
  wire ena;
  wire [2:0] fSCL;
  wire [2:0] fSDA;
  wire [13:0] filter_cnt;
  input nReset;
  wire nReset;
  wire sSCL;
  wire sSDA;
  input scl_i;
  wire scl_i;
  output scl_o;
  wire scl_o;
  output scl_oen;
  wire scl_oen;
  wire sda_chk;
  input sda_i;
  wire sda_i;
  output sda_o;
  wire sda_o;
  output sda_oen;
  wire sda_oen;
  wire slave_wait;
  wire sta_condition;
  wire sto_condition;
  sky130_fd_sc_hd__clkinv_1 _0761_ (
    .A(_0378_),
    .Y(_0505_)
  );
  sky130_fd_sc_hd__clkinv_1 _0762_ (
    .A(_0458_),
    .Y(_0506_)
  );
  sky130_fd_sc_hd__clkinv_1 _0763_ (
    .A(_0432_),
    .Y(_0507_)
  );
  sky130_fd_sc_hd__clkinv_1 _0764_ (
    .A(_0433_),
    .Y(_0508_)
  );
  sky130_fd_sc_hd__clkinv_1 _0765_ (
    .A(_0436_),
    .Y(_0509_)
  );
  sky130_fd_sc_hd__clkinv_1 _0766_ (
    .A(_0441_),
    .Y(_0510_)
  );
  sky130_fd_sc_hd__clkinv_1 _0767_ (
    .A(_0429_),
    .Y(_0511_)
  );
  sky130_fd_sc_hd__clkinv_1 _0768_ (
    .A(_0431_),
    .Y(_0512_)
  );
  sky130_fd_sc_hd__clkinv_1 _0769_ (
    .A(_0430_),
    .Y(_0513_)
  );
  sky130_fd_sc_hd__clkinv_1 _0770_ (
    .A(_0447_),
    .Y(_0514_)
  );
  sky130_fd_sc_hd__clkinv_1 _0771_ (
    .A(_0483_),
    .Y(_0515_)
  );
  sky130_fd_sc_hd__clkinv_1 _0772_ (
    .A(_0712_),
    .Y(_0516_)
  );
  sky130_fd_sc_hd__or3_1 _0773_ (
    .A(_0471_),
    .B(_0464_),
    .C(_0472_),
    .X(_0517_)
  );
  sky130_fd_sc_hd__or3_1 _0774_ (
    .A(_0473_),
    .B(_0475_),
    .C(_0474_),
    .X(_0518_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0775_ (
    .A(_0473_),
    .SLEEP(_0517_),
    .X(_0519_)
  );
  sky130_fd_sc_hd__nor3_1 _0776_ (
    .A(_0476_),
    .B(_0517_),
    .C(_0518_),
    .Y(_0520_)
  );
  sky130_fd_sc_hd__nor4_1 _0777_ (
    .A(_0477_),
    .B(_0476_),
    .C(_0517_),
    .D(_0518_),
    .Y(_0521_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0778_ (
    .A(_0521_),
    .SLEEP(_0478_),
    .X(_0522_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0779_ (
    .A(_0522_),
    .SLEEP(_0479_),
    .X(_0523_)
  );
  sky130_fd_sc_hd__or4b_1 _0780_ (
    .A(_0479_),
    .B(_0478_),
    .C(_0465_),
    .D_N(_0521_),
    .X(_0524_)
  );
  sky130_fd_sc_hd__nor2_1 _0781_ (
    .A(_0466_),
    .B(_0524_),
    .Y(_0525_)
  );
  sky130_fd_sc_hd__or4_1 _0782_ (
    .A(_0466_),
    .B(_0468_),
    .C(_0467_),
    .D(_0524_),
    .X(_0526_)
  );
  sky130_fd_sc_hd__nand2_1 _0783_ (
    .A(_0480_),
    .B(_0711_),
    .Y(_0527_)
  );
  sky130_fd_sc_hd__o21a_1 _0784_ (
    .A1(_0709_),
    .A2(_0527_),
    .B1(_0484_),
    .X(_0528_)
  );
  sky130_fd_sc_hd__o21ai_0 _0785_ (
    .A1(_0469_),
    .A2(_0526_),
    .B1(_0528_),
    .Y(_0529_)
  );
  sky130_fd_sc_hd__o31ai_1 _0786_ (
    .A1(_0470_),
    .A2(_0469_),
    .A3(_0526_),
    .B1(_0528_),
    .Y(_0356_)
  );
  sky130_fd_sc_hd__nor2_1 _0787_ (
    .A(_0438_),
    .B(_0439_),
    .Y(_0530_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0788_ (
    .A(_0428_),
    .SLEEP(_0429_),
    .X(_0531_)
  );
  sky130_fd_sc_hd__nor2_1 _0789_ (
    .A(_0427_),
    .B(_0426_),
    .Y(_0532_)
  );
  sky130_fd_sc_hd__nor2_1 _0790_ (
    .A(_0441_),
    .B(_0440_),
    .Y(_0533_)
  );
  sky130_fd_sc_hd__or4_1 _0791_ (
    .A(_0441_),
    .B(_0440_),
    .C(_0427_),
    .D(_0426_),
    .X(_0534_)
  );
  sky130_fd_sc_hd__nor3_1 _0792_ (
    .A(_0431_),
    .B(_0430_),
    .C(_0534_),
    .Y(_0535_)
  );
  sky130_fd_sc_hd__or4_1 _0793_ (
    .A(_0428_),
    .B(_0429_),
    .C(_0431_),
    .D(_0430_),
    .X(_0536_)
  );
  sky130_fd_sc_hd__nor2_1 _0794_ (
    .A(_0534_),
    .B(_0536_),
    .Y(_0537_)
  );
  sky130_fd_sc_hd__or4_1 _0795_ (
    .A(_0433_),
    .B(_0425_),
    .C(_0435_),
    .D(_0434_),
    .X(_0538_)
  );
  sky130_fd_sc_hd__nor4_1 _0796_ (
    .A(_0432_),
    .B(_0534_),
    .C(_0536_),
    .D(_0538_),
    .Y(_0539_)
  );
  sky130_fd_sc_hd__and4b_1 _0797_ (
    .A_N(_0437_),
    .B(_0436_),
    .C(_0530_),
    .D(_0539_),
    .X(_0540_)
  );
  sky130_fd_sc_hd__or3_1 _0798_ (
    .A(_0432_),
    .B(_0431_),
    .C(_0430_),
    .X(_0541_)
  );
  sky130_fd_sc_hd__nor2_1 _0799_ (
    .A(_0437_),
    .B(_0436_),
    .Y(_0542_)
  );
  sky130_fd_sc_hd__or4_1 _0800_ (
    .A(_0437_),
    .B(_0436_),
    .C(_0438_),
    .D(_0439_),
    .X(_0543_)
  );
  sky130_fd_sc_hd__nor2_1 _0801_ (
    .A(_0538_),
    .B(_0543_),
    .Y(_0544_)
  );
  sky130_fd_sc_hd__nor3_1 _0802_ (
    .A(_0531_),
    .B(_0538_),
    .C(_0543_),
    .Y(_0545_)
  );
  sky130_fd_sc_hd__nor4_1 _0803_ (
    .A(_0531_),
    .B(_0538_),
    .C(_0541_),
    .D(_0543_),
    .Y(_0546_)
  );
  sky130_fd_sc_hd__nand4_1 _0804_ (
    .A(_0510_),
    .B(_0440_),
    .C(_0532_),
    .D(_0546_),
    .Y(_0547_)
  );
  sky130_fd_sc_hd__nor2_1 _0805_ (
    .A(_0432_),
    .B(_0534_),
    .Y(_0548_)
  );
  sky130_fd_sc_hd__nor2_1 _0806_ (
    .A(_0534_),
    .B(_0541_),
    .Y(_0549_)
  );
  sky130_fd_sc_hd__nand4_1 _0807_ (
    .A(_0428_),
    .B(_0511_),
    .C(_0544_),
    .D(_0549_),
    .Y(_0550_)
  );
  sky130_fd_sc_hd__nand3_1 _0808_ (
    .A(_0432_),
    .B(_0535_),
    .C(_0545_),
    .Y(_0551_)
  );
  sky130_fd_sc_hd__nand4b_1 _0809_ (
    .A_N(_0540_),
    .B(_0547_),
    .C(_0550_),
    .D(_0551_),
    .Y(_0552_)
  );
  sky130_fd_sc_hd__and3_1 _0810_ (
    .A(_0505_),
    .B(_0458_),
    .C(_0552_),
    .X(_0357_)
  );
  sky130_fd_sc_hd__or3_1 _0811_ (
    .A(_0496_),
    .B(_0491_),
    .C(_0497_),
    .X(_0553_)
  );
  sky130_fd_sc_hd__or3_1 _0812_ (
    .A(_0498_),
    .B(_0499_),
    .C(_0553_),
    .X(_0554_)
  );
  sky130_fd_sc_hd__nor2_1 _0813_ (
    .A(_0500_),
    .B(_0554_),
    .Y(_0555_)
  );
  sky130_fd_sc_hd__or4_1 _0814_ (
    .A(_0500_),
    .B(_0502_),
    .C(_0501_),
    .D(_0554_),
    .X(_0556_)
  );
  sky130_fd_sc_hd__nor2_1 _0815_ (
    .A(_0503_),
    .B(_0556_),
    .Y(_0557_)
  );
  sky130_fd_sc_hd__or4_1 _0816_ (
    .A(_0504_),
    .B(_0503_),
    .C(_0492_),
    .D(_0556_),
    .X(_0558_)
  );
  sky130_fd_sc_hd__nor3_1 _0817_ (
    .A(_0493_),
    .B(_0494_),
    .C(_0558_),
    .Y(_0559_)
  );
  sky130_fd_sc_hd__or3_1 _0818_ (
    .A(_0493_),
    .B(_0495_),
    .C(_0494_),
    .X(_0560_)
  );
  sky130_fd_sc_hd__nor2_1 _0819_ (
    .A(_0558_),
    .B(_0560_),
    .Y(_0561_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0820_ (
    .A(_0558_),
    .SLEEP(_0560_),
    .X(_0562_)
  );
  sky130_fd_sc_hd__o21ai_0 _0821_ (
    .A1(_0450_),
    .A2(_0562_),
    .B1(_0484_),
    .Y(_0563_)
  );
  sky130_fd_sc_hd__nor2_1 _0822_ (
    .A(_0491_),
    .B(_0563_),
    .Y(_0358_)
  );
  sky130_fd_sc_hd__xor2_1 _0823_ (
    .A(_0496_),
    .B(_0491_),
    .X(_0564_)
  );
  sky130_fd_sc_hd__o21ai_0 _0824_ (
    .A1(_0451_),
    .A2(_0562_),
    .B1(_0484_),
    .Y(_0565_)
  );
  sky130_fd_sc_hd__nor2_1 _0825_ (
    .A(_0564_),
    .B(_0565_),
    .Y(_0363_)
  );
  sky130_fd_sc_hd__o21ai_0 _0826_ (
    .A1(_0496_),
    .A2(_0491_),
    .B1(_0497_),
    .Y(_0566_)
  );
  sky130_fd_sc_hd__o21ai_0 _0827_ (
    .A1(_0452_),
    .A2(_0562_),
    .B1(_0484_),
    .Y(_0567_)
  );
  sky130_fd_sc_hd__a21oi_1 _0828_ (
    .A1(_0553_),
    .A2(_0566_),
    .B1(_0567_),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__xor2_1 _0829_ (
    .A(_0498_),
    .B(_0553_),
    .X(_0568_)
  );
  sky130_fd_sc_hd__o21ai_0 _0830_ (
    .A1(_0453_),
    .A2(_0562_),
    .B1(_0484_),
    .Y(_0569_)
  );
  sky130_fd_sc_hd__nor2_1 _0831_ (
    .A(_0568_),
    .B(_0569_),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__o21ai_0 _0832_ (
    .A1(_0498_),
    .A2(_0553_),
    .B1(_0499_),
    .Y(_0570_)
  );
  sky130_fd_sc_hd__o21ai_0 _0833_ (
    .A1(_0454_),
    .A2(_0562_),
    .B1(_0484_),
    .Y(_0571_)
  );
  sky130_fd_sc_hd__a21oi_1 _0834_ (
    .A1(_0554_),
    .A2(_0570_),
    .B1(_0571_),
    .Y(_0366_)
  );
  sky130_fd_sc_hd__xor2_1 _0835_ (
    .A(_0500_),
    .B(_0554_),
    .X(_0572_)
  );
  sky130_fd_sc_hd__o21ai_0 _0836_ (
    .A1(_0455_),
    .A2(_0562_),
    .B1(_0484_),
    .Y(_0573_)
  );
  sky130_fd_sc_hd__nor2_1 _0837_ (
    .A(_0572_),
    .B(_0573_),
    .Y(_0367_)
  );
  sky130_fd_sc_hd__xnor2_1 _0838_ (
    .A(_0501_),
    .B(_0555_),
    .Y(_0574_)
  );
  sky130_fd_sc_hd__o21ai_0 _0839_ (
    .A1(_0456_),
    .A2(_0562_),
    .B1(_0484_),
    .Y(_0575_)
  );
  sky130_fd_sc_hd__nor2_1 _0840_ (
    .A(_0574_),
    .B(_0575_),
    .Y(_0368_)
  );
  sky130_fd_sc_hd__o31ai_1 _0841_ (
    .A1(_0500_),
    .A2(_0501_),
    .A3(_0554_),
    .B1(_0502_),
    .Y(_0576_)
  );
  sky130_fd_sc_hd__o21ai_0 _0842_ (
    .A1(_0457_),
    .A2(_0562_),
    .B1(_0484_),
    .Y(_0577_)
  );
  sky130_fd_sc_hd__a21oi_1 _0843_ (
    .A1(_0556_),
    .A2(_0576_),
    .B1(_0577_),
    .Y(_0369_)
  );
  sky130_fd_sc_hd__xnor2_1 _0844_ (
    .A(_0503_),
    .B(_0556_),
    .Y(_0578_)
  );
  sky130_fd_sc_hd__o311a_1 _0845_ (
    .A1(_0443_),
    .A2(_0558_),
    .A3(_0560_),
    .B1(_0578_),
    .C1(_0484_),
    .X(_0370_)
  );
  sky130_fd_sc_hd__xor2_1 _0846_ (
    .A(_0504_),
    .B(_0557_),
    .X(_0579_)
  );
  sky130_fd_sc_hd__o211a_1 _0847_ (
    .A1(_0444_),
    .A2(_0562_),
    .B1(_0579_),
    .C1(_0484_),
    .X(_0371_)
  );
  sky130_fd_sc_hd__o31ai_1 _0848_ (
    .A1(_0504_),
    .A2(_0503_),
    .A3(_0556_),
    .B1(_0492_),
    .Y(_0580_)
  );
  sky130_fd_sc_hd__nor2_1 _0849_ (
    .A(_0445_),
    .B(_0560_),
    .Y(_0581_)
  );
  sky130_fd_sc_hd__o21ai_0 _0850_ (
    .A1(_0558_),
    .A2(_0581_),
    .B1(_0580_),
    .Y(_0582_)
  );
  sky130_fd_sc_hd__and2_0 _0851_ (
    .A(_0484_),
    .B(_0582_),
    .X(_0359_)
  );
  sky130_fd_sc_hd__xnor2_1 _0852_ (
    .A(_0493_),
    .B(_0558_),
    .Y(_0583_)
  );
  sky130_fd_sc_hd__a22oi_1 _0853_ (
    .A1(_0446_),
    .A2(_0561_),
    .B1(_0583_),
    .B2(_0560_),
    .Y(_0584_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0854_ (
    .A(_0484_),
    .SLEEP(_0584_),
    .X(_0360_)
  );
  sky130_fd_sc_hd__o21ai_0 _0855_ (
    .A1(_0493_),
    .A2(_0558_),
    .B1(_0494_),
    .Y(_0585_)
  );
  sky130_fd_sc_hd__o21ai_0 _0856_ (
    .A1(_0495_),
    .A2(_0447_),
    .B1(_0559_),
    .Y(_0586_)
  );
  sky130_fd_sc_hd__a21boi_0 _0857_ (
    .A1(_0585_),
    .A2(_0586_),
    .B1_N(_0484_),
    .Y(_0361_)
  );
  sky130_fd_sc_hd__nand2b_1 _0858_ (
    .A_N(_0559_),
    .B(_0495_),
    .Y(_0587_)
  );
  sky130_fd_sc_hd__nand2_1 _0859_ (
    .A(_0448_),
    .B(_0561_),
    .Y(_0588_)
  );
  sky130_fd_sc_hd__a21boi_0 _0860_ (
    .A1(_0587_),
    .A2(_0588_),
    .B1_N(_0484_),
    .Y(_0362_)
  );
  sky130_fd_sc_hd__a21oi_1 _0861_ (
    .A1(_0711_),
    .A2(_0515_),
    .B1(_0714_),
    .Y(_0589_)
  );
  sky130_fd_sc_hd__nor2_1 _0862_ (
    .A(_0709_),
    .B(_0589_),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__maj3_1 _0863_ (
    .A(_0487_),
    .B(_0486_),
    .C(_0485_),
    .X(_0372_)
  );
  sky130_fd_sc_hd__maj3_1 _0864_ (
    .A(_0490_),
    .B(_0489_),
    .C(_0488_),
    .X(_0373_)
  );
  sky130_fd_sc_hd__nand2_1 _0865_ (
    .A(_0709_),
    .B(_0481_),
    .Y(_0590_)
  );
  sky130_fd_sc_hd__nor2_1 _0866_ (
    .A(_0710_),
    .B(_0590_),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__nand2_1 _0867_ (
    .A(_0709_),
    .B(_0710_),
    .Y(_0591_)
  );
  sky130_fd_sc_hd__nor2_1 _0868_ (
    .A(_0481_),
    .B(_0591_),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__nor2_1 _0869_ (
    .A(_0422_),
    .B(_0715_),
    .Y(_0592_)
  );
  sky130_fd_sc_hd__nor2_1 _0870_ (
    .A(_0716_),
    .B(_0592_),
    .Y(_0355_)
  );
  sky130_fd_sc_hd__nand2_1 _0871_ (
    .A(_0545_),
    .B(_0549_),
    .Y(_0593_)
  );
  sky130_fd_sc_hd__nand3b_1 _0872_ (
    .A_N(_0463_),
    .B(_0593_),
    .C(_0716_),
    .Y(_0594_)
  );
  sky130_fd_sc_hd__nand2_1 _0873_ (
    .A(_0712_),
    .B(_0713_),
    .Y(_0595_)
  );
  sky130_fd_sc_hd__o21ai_0 _0874_ (
    .A1(_0710_),
    .A2(_0595_),
    .B1(_0594_),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0875_ (
    .A(_0709_),
    .SLEEP(_0480_),
    .X(_0377_)
  );
  sky130_fd_sc_hd__nor2_1 _0876_ (
    .A(_0378_),
    .B(_0458_),
    .Y(_0596_)
  );
  sky130_fd_sc_hd__nand4b_1 _0877_ (
    .A_N(_0438_),
    .B(_0439_),
    .C(_0539_),
    .D(_0542_),
    .Y(_0597_)
  );
  sky130_fd_sc_hd__nor4_1 _0878_ (
    .A(_0432_),
    .B(_0433_),
    .C(_0425_),
    .D(_0543_),
    .Y(_0598_)
  );
  sky130_fd_sc_hd__nand4b_1 _0879_ (
    .A_N(_0435_),
    .B(_0434_),
    .C(_0537_),
    .D(_0598_),
    .Y(_0599_)
  );
  sky130_fd_sc_hd__nand2_1 _0880_ (
    .A(_0597_),
    .B(_0599_),
    .Y(_0600_)
  );
  sky130_fd_sc_hd__nor4_1 _0881_ (
    .A(_0432_),
    .B(_0435_),
    .C(_0434_),
    .D(_0543_),
    .Y(_0601_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0882_ (
    .A(_0425_),
    .SLEEP(_0433_),
    .X(_0602_)
  );
  sky130_fd_sc_hd__nor2_1 _0883_ (
    .A(_0508_),
    .B(_0425_),
    .Y(_0603_)
  );
  sky130_fd_sc_hd__nand3_1 _0884_ (
    .A(_0537_),
    .B(_0601_),
    .C(_0603_),
    .Y(_0604_)
  );
  sky130_fd_sc_hd__o211ai_1 _0885_ (
    .A1(_0602_),
    .A2(_0603_),
    .B1(_0537_),
    .C1(_0601_),
    .Y(_0605_)
  );
  sky130_fd_sc_hd__nand3_1 _0886_ (
    .A(_0597_),
    .B(_0599_),
    .C(_0605_),
    .Y(_0606_)
  );
  sky130_fd_sc_hd__nand4_1 _0887_ (
    .A(_0437_),
    .B(_0509_),
    .C(_0530_),
    .D(_0539_),
    .Y(_0607_)
  );
  sky130_fd_sc_hd__nand4b_1 _0888_ (
    .A_N(_0440_),
    .B(_0532_),
    .C(_0546_),
    .D(_0441_),
    .Y(_0608_)
  );
  sky130_fd_sc_hd__nand2_1 _0889_ (
    .A(_0607_),
    .B(_0608_),
    .Y(_0609_)
  );
  sky130_fd_sc_hd__nor2_1 _0890_ (
    .A(_0512_),
    .B(_0430_),
    .Y(_0610_)
  );
  sky130_fd_sc_hd__nand3_1 _0891_ (
    .A(_0545_),
    .B(_0548_),
    .C(_0610_),
    .Y(_0611_)
  );
  sky130_fd_sc_hd__nor2_1 _0892_ (
    .A(_0431_),
    .B(_0513_),
    .Y(_0612_)
  );
  sky130_fd_sc_hd__o211ai_1 _0893_ (
    .A1(_0610_),
    .A2(_0612_),
    .B1(_0545_),
    .C1(_0548_),
    .Y(_0613_)
  );
  sky130_fd_sc_hd__nand4b_1 _0894_ (
    .A_N(_0428_),
    .B(_0429_),
    .C(_0544_),
    .D(_0549_),
    .Y(_0614_)
  );
  sky130_fd_sc_hd__nand4_1 _0895_ (
    .A(_0607_),
    .B(_0608_),
    .C(_0613_),
    .D(_0614_),
    .Y(_0615_)
  );
  sky130_fd_sc_hd__nand4b_1 _0896_ (
    .A_N(_0439_),
    .B(_0539_),
    .C(_0542_),
    .D(_0438_),
    .Y(_0616_)
  );
  sky130_fd_sc_hd__nand4b_1 _0897_ (
    .A_N(_0434_),
    .B(_0537_),
    .C(_0598_),
    .D(_0435_),
    .Y(_0617_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0898_ (
    .A(_0426_),
    .SLEEP(_0427_),
    .X(_0618_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0899_ (
    .A(_0427_),
    .SLEEP(_0426_),
    .X(_0619_)
  );
  sky130_fd_sc_hd__o211ai_1 _0900_ (
    .A1(_0618_),
    .A2(_0619_),
    .B1(_0533_),
    .C1(_0546_),
    .Y(_0620_)
  );
  sky130_fd_sc_hd__nand3_1 _0901_ (
    .A(_0616_),
    .B(_0617_),
    .C(_0620_),
    .Y(_0621_)
  );
  sky130_fd_sc_hd__nor4_1 _0902_ (
    .A(_0552_),
    .B(_0606_),
    .C(_0615_),
    .D(_0621_),
    .Y(_0622_)
  );
  sky130_fd_sc_hd__nand4b_1 _0903_ (
    .A_N(_0440_),
    .B(_0532_),
    .C(_0546_),
    .D(_0441_),
    .Y(_0623_)
  );
  sky130_fd_sc_hd__nand4b_1 _0904_ (
    .A_N(_0426_),
    .B(_0533_),
    .C(_0546_),
    .D(_0427_),
    .Y(_0624_)
  );
  sky130_fd_sc_hd__nand4b_1 _0905_ (
    .A_N(_0427_),
    .B(_0426_),
    .C(_0533_),
    .D(_0546_),
    .Y(_0625_)
  );
  sky130_fd_sc_hd__o21ai_0 _0906_ (
    .A1(_0506_),
    .A2(_0622_),
    .B1(_0505_),
    .Y(_0626_)
  );
  sky130_fd_sc_hd__a31oi_1 _0907_ (
    .A1(_0505_),
    .A2(_0593_),
    .A3(_0622_),
    .B1(_0596_),
    .Y(_0627_)
  );
  sky130_fd_sc_hd__nor2_1 _0908_ (
    .A(_0462_),
    .B(_0461_),
    .Y(_0628_)
  );
  sky130_fd_sc_hd__nor4b_1 _0909_ (
    .A(_0460_),
    .B(_0462_),
    .C(_0461_),
    .D_N(_0459_),
    .Y(_0629_)
  );
  sky130_fd_sc_hd__and3_1 _0910_ (
    .A(_0505_),
    .B(_0622_),
    .C(_0629_),
    .X(_0630_)
  );
  sky130_fd_sc_hd__mux2_1 _0911_ (
    .A0(_0425_),
    .A1(_0630_),
    .S(_0627_),
    .X(_0379_)
  );
  sky130_fd_sc_hd__nand4_1 _0912_ (
    .A(_0505_),
    .B(_0537_),
    .C(_0601_),
    .D(_0602_),
    .Y(_0631_)
  );
  sky130_fd_sc_hd__mux2i_1 _0913_ (
    .A0(_0508_),
    .A1(_0631_),
    .S(_0627_),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__nor2_1 _0914_ (
    .A(_0378_),
    .B(_0604_),
    .Y(_0632_)
  );
  sky130_fd_sc_hd__mux2_1 _0915_ (
    .A0(_0434_),
    .A1(_0632_),
    .S(_0627_),
    .X(_0381_)
  );
  sky130_fd_sc_hd__nor2_1 _0916_ (
    .A(_0378_),
    .B(_0599_),
    .Y(_0633_)
  );
  sky130_fd_sc_hd__mux2_1 _0917_ (
    .A0(_0435_),
    .A1(_0633_),
    .S(_0627_),
    .X(_0382_)
  );
  sky130_fd_sc_hd__a2111oi_0 _0918_ (
    .A1(_0593_),
    .A2(_0622_),
    .B1(_0596_),
    .C1(_0378_),
    .D1(_0617_),
    .Y(_0634_)
  );
  sky130_fd_sc_hd__o21bai_1 _0919_ (
    .A1(_0509_),
    .A2(_0627_),
    .B1_N(_0634_),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__nand2_1 _0920_ (
    .A(_0460_),
    .B(_0628_),
    .Y(_0635_)
  );
  sky130_fd_sc_hd__nor4b_1 _0921_ (
    .A(_0378_),
    .B(_0635_),
    .C(_0459_),
    .D_N(_0622_),
    .Y(_0636_)
  );
  sky130_fd_sc_hd__mux2_1 _0922_ (
    .A0(_0437_),
    .A1(_0636_),
    .S(_0627_),
    .X(_0384_)
  );
  sky130_fd_sc_hd__nor2_1 _0923_ (
    .A(_0378_),
    .B(_0607_),
    .Y(_0637_)
  );
  sky130_fd_sc_hd__mux2_1 _0924_ (
    .A0(_0438_),
    .A1(_0637_),
    .S(_0627_),
    .X(_0385_)
  );
  sky130_fd_sc_hd__nor2_1 _0925_ (
    .A(_0378_),
    .B(_0616_),
    .Y(_0638_)
  );
  sky130_fd_sc_hd__mux2_1 _0926_ (
    .A0(_0439_),
    .A1(_0638_),
    .S(_0627_),
    .X(_0386_)
  );
  sky130_fd_sc_hd__nor2_1 _0927_ (
    .A(_0378_),
    .B(_0597_),
    .Y(_0639_)
  );
  sky130_fd_sc_hd__mux2_1 _0928_ (
    .A0(_0440_),
    .A1(_0639_),
    .S(_0627_),
    .X(_0387_)
  );
  sky130_fd_sc_hd__nor2_1 _0929_ (
    .A(_0459_),
    .B(_0460_),
    .Y(_0640_)
  );
  sky130_fd_sc_hd__nor2_1 _0930_ (
    .A(_0378_),
    .B(_0461_),
    .Y(_0641_)
  );
  sky130_fd_sc_hd__nand4_1 _0931_ (
    .A(_0462_),
    .B(_0622_),
    .C(_0640_),
    .D(_0641_),
    .Y(_0642_)
  );
  sky130_fd_sc_hd__mux2i_1 _0932_ (
    .A0(_0510_),
    .A1(_0642_),
    .S(_0627_),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__nor2_1 _0933_ (
    .A(_0378_),
    .B(_0623_),
    .Y(_0643_)
  );
  sky130_fd_sc_hd__mux2_1 _0934_ (
    .A0(_0426_),
    .A1(_0643_),
    .S(_0627_),
    .X(_0389_)
  );
  sky130_fd_sc_hd__nor2_1 _0935_ (
    .A(_0378_),
    .B(_0625_),
    .Y(_0644_)
  );
  sky130_fd_sc_hd__mux2_1 _0936_ (
    .A0(_0427_),
    .A1(_0644_),
    .S(_0627_),
    .X(_0390_)
  );
  sky130_fd_sc_hd__nor2_1 _0937_ (
    .A(_0378_),
    .B(_0624_),
    .Y(_0645_)
  );
  sky130_fd_sc_hd__mux2_1 _0938_ (
    .A0(_0428_),
    .A1(_0645_),
    .S(_0627_),
    .X(_0391_)
  );
  sky130_fd_sc_hd__nor2_1 _0939_ (
    .A(_0378_),
    .B(_0462_),
    .Y(_0646_)
  );
  sky130_fd_sc_hd__nand4_1 _0940_ (
    .A(_0461_),
    .B(_0622_),
    .C(_0640_),
    .D(_0646_),
    .Y(_0647_)
  );
  sky130_fd_sc_hd__mux2i_1 _0941_ (
    .A0(_0511_),
    .A1(_0647_),
    .S(_0627_),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__a2111oi_0 _0942_ (
    .A1(_0593_),
    .A2(_0622_),
    .B1(_0596_),
    .C1(_0378_),
    .D1(_0614_),
    .Y(_0648_)
  );
  sky130_fd_sc_hd__o21bai_1 _0943_ (
    .A1(_0513_),
    .A2(_0627_),
    .B1_N(_0648_),
    .Y(_0393_)
  );
  sky130_fd_sc_hd__nand4_1 _0944_ (
    .A(_0505_),
    .B(_0545_),
    .C(_0548_),
    .D(_0612_),
    .Y(_0649_)
  );
  sky130_fd_sc_hd__mux2i_1 _0945_ (
    .A0(_0512_),
    .A1(_0649_),
    .S(_0627_),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__a2111oi_0 _0946_ (
    .A1(_0593_),
    .A2(_0622_),
    .B1(_0596_),
    .C1(_0378_),
    .D1(_0611_),
    .Y(_0650_)
  );
  sky130_fd_sc_hd__o21bai_1 _0947_ (
    .A1(_0507_),
    .A2(_0626_),
    .B1_N(_0650_),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__nand3_1 _0948_ (
    .A(_0547_),
    .B(_0604_),
    .C(_0613_),
    .Y(_0651_)
  );
  sky130_fd_sc_hd__o31a_1 _0949_ (
    .A1(_0600_),
    .A2(_0621_),
    .A3(_0651_),
    .B1(_0458_),
    .X(_0652_)
  );
  sky130_fd_sc_hd__nand3_1 _0950_ (
    .A(_0550_),
    .B(_0551_),
    .C(_0614_),
    .Y(_0653_)
  );
  sky130_fd_sc_hd__nor3_1 _0951_ (
    .A(_0540_),
    .B(_0609_),
    .C(_0653_),
    .Y(_0654_)
  );
  sky130_fd_sc_hd__o22ai_1 _0952_ (
    .A1(_0711_),
    .A2(_0652_),
    .B1(_0654_),
    .B2(_0506_),
    .Y(_0655_)
  );
  sky130_fd_sc_hd__nand2_1 _0953_ (
    .A(_0505_),
    .B(_0655_),
    .Y(_0396_)
  );
  sky130_fd_sc_hd__and3_1 _0954_ (
    .A(_0505_),
    .B(_0547_),
    .C(_0550_),
    .X(_0656_)
  );
  sky130_fd_sc_hd__nand4_1 _0955_ (
    .A(_0605_),
    .B(_0608_),
    .C(_0620_),
    .D(_0656_),
    .Y(_0657_)
  );
  sky130_fd_sc_hd__nand3_1 _0956_ (
    .A(_0551_),
    .B(_0613_),
    .C(_0614_),
    .Y(_0658_)
  );
  sky130_fd_sc_hd__a21o_1 _0957_ (
    .A1(_0482_),
    .A2(_0658_),
    .B1(_0657_),
    .X(_0659_)
  );
  sky130_fd_sc_hd__mux2_1 _0958_ (
    .A0(_0713_),
    .A1(_0659_),
    .S(_0626_),
    .X(_0397_)
  );
  sky130_fd_sc_hd__o21bai_1 _0959_ (
    .A1(_0516_),
    .A2(_0627_),
    .B1_N(_0650_),
    .Y(_0398_)
  );
  sky130_fd_sc_hd__nand2_1 _0960_ (
    .A(_0506_),
    .B(_0463_),
    .Y(_0660_)
  );
  sky130_fd_sc_hd__o31ai_1 _0961_ (
    .A1(_0506_),
    .A2(_0459_),
    .A3(_0635_),
    .B1(_0660_),
    .Y(_0399_)
  );
  sky130_fd_sc_hd__nand2_1 _0962_ (
    .A(_0423_),
    .B(_0561_),
    .Y(_0661_)
  );
  sky130_fd_sc_hd__nand2_1 _0963_ (
    .A(_0485_),
    .B(_0562_),
    .Y(_0662_)
  );
  sky130_fd_sc_hd__nand2_1 _0964_ (
    .A(_0661_),
    .B(_0662_),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__nand2_1 _0965_ (
    .A(_0485_),
    .B(_0561_),
    .Y(_0663_)
  );
  sky130_fd_sc_hd__nand2_1 _0966_ (
    .A(_0486_),
    .B(_0562_),
    .Y(_0664_)
  );
  sky130_fd_sc_hd__nand2_1 _0967_ (
    .A(_0663_),
    .B(_0664_),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__nand2_1 _0968_ (
    .A(_0486_),
    .B(_0561_),
    .Y(_0665_)
  );
  sky130_fd_sc_hd__nand2_1 _0969_ (
    .A(_0487_),
    .B(_0562_),
    .Y(_0666_)
  );
  sky130_fd_sc_hd__nand2_1 _0970_ (
    .A(_0665_),
    .B(_0666_),
    .Y(_0402_)
  );
  sky130_fd_sc_hd__nand2_1 _0971_ (
    .A(_0424_),
    .B(_0561_),
    .Y(_0667_)
  );
  sky130_fd_sc_hd__nand2_1 _0972_ (
    .A(_0488_),
    .B(_0562_),
    .Y(_0668_)
  );
  sky130_fd_sc_hd__nand2_1 _0973_ (
    .A(_0667_),
    .B(_0668_),
    .Y(_0403_)
  );
  sky130_fd_sc_hd__nand2_1 _0974_ (
    .A(_0488_),
    .B(_0561_),
    .Y(_0669_)
  );
  sky130_fd_sc_hd__nand2_1 _0975_ (
    .A(_0489_),
    .B(_0562_),
    .Y(_0670_)
  );
  sky130_fd_sc_hd__nand2_1 _0976_ (
    .A(_0669_),
    .B(_0670_),
    .Y(_0404_)
  );
  sky130_fd_sc_hd__nand2_1 _0977_ (
    .A(_0489_),
    .B(_0561_),
    .Y(_0671_)
  );
  sky130_fd_sc_hd__nand2_1 _0978_ (
    .A(_0490_),
    .B(_0562_),
    .Y(_0672_)
  );
  sky130_fd_sc_hd__nand2_1 _0979_ (
    .A(_0671_),
    .B(_0672_),
    .Y(_0405_)
  );
  sky130_fd_sc_hd__xor2_1 _0980_ (
    .A(_0464_),
    .B(_0714_),
    .X(_0673_)
  );
  sky130_fd_sc_hd__nand2_1 _0981_ (
    .A(_0442_),
    .B(_0356_),
    .Y(_0674_)
  );
  sky130_fd_sc_hd__o21ai_0 _0982_ (
    .A1(_0356_),
    .A2(_0673_),
    .B1(_0674_),
    .Y(_0406_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0983_ (
    .A(_0714_),
    .SLEEP(_0356_),
    .X(_0675_)
  );
  sky130_fd_sc_hd__o311ai_0 _0984_ (
    .A1(_0470_),
    .A2(_0469_),
    .A3(_0526_),
    .B1(_0528_),
    .C1(_0714_),
    .Y(_0676_)
  );
  sky130_fd_sc_hd__xor2_1 _0985_ (
    .A(_0471_),
    .B(_0464_),
    .X(_0677_)
  );
  sky130_fd_sc_hd__nor3_1 _0986_ (
    .A(_0714_),
    .B(_0356_),
    .C(_0677_),
    .Y(_0678_)
  );
  sky130_fd_sc_hd__a221o_1 _0987_ (
    .A1(_0449_),
    .A2(_0356_),
    .B1(_0675_),
    .B2(_0471_),
    .C1(_0678_),
    .X(_0407_)
  );
  sky130_fd_sc_hd__o21ai_0 _0988_ (
    .A1(_0471_),
    .A2(_0464_),
    .B1(_0472_),
    .Y(_0679_)
  );
  sky130_fd_sc_hd__a211oi_1 _0989_ (
    .A1(_0517_),
    .A2(_0679_),
    .B1(_0356_),
    .C1(_0714_),
    .Y(_0680_)
  );
  sky130_fd_sc_hd__a221o_1 _0990_ (
    .A1(_0450_),
    .A2(_0356_),
    .B1(_0675_),
    .B2(_0472_),
    .C1(_0680_),
    .X(_0408_)
  );
  sky130_fd_sc_hd__o21ai_0 _0991_ (
    .A1(_0714_),
    .A2(_0517_),
    .B1(_0473_),
    .Y(_0681_)
  );
  sky130_fd_sc_hd__o21ai_0 _0992_ (
    .A1(_0714_),
    .A2(_0519_),
    .B1(_0681_),
    .Y(_0682_)
  );
  sky130_fd_sc_hd__mux2_1 _0993_ (
    .A0(_0682_),
    .A1(_0451_),
    .S(_0356_),
    .X(_0409_)
  );
  sky130_fd_sc_hd__nor3_1 _0994_ (
    .A(_0474_),
    .B(_0714_),
    .C(_0519_),
    .Y(_0683_)
  );
  sky130_fd_sc_hd__o21a_1 _0995_ (
    .A1(_0714_),
    .A2(_0519_),
    .B1(_0474_),
    .X(_0684_)
  );
  sky130_fd_sc_hd__nor2_1 _0996_ (
    .A(_0683_),
    .B(_0684_),
    .Y(_0685_)
  );
  sky130_fd_sc_hd__nand2_1 _0997_ (
    .A(_0452_),
    .B(_0356_),
    .Y(_0686_)
  );
  sky130_fd_sc_hd__o21ai_0 _0998_ (
    .A1(_0356_),
    .A2(_0685_),
    .B1(_0686_),
    .Y(_0410_)
  );
  sky130_fd_sc_hd__xnor2_1 _0999_ (
    .A(_0475_),
    .B(_0683_),
    .Y(_0687_)
  );
  sky130_fd_sc_hd__nand2_1 _1000_ (
    .A(_0453_),
    .B(_0356_),
    .Y(_0688_)
  );
  sky130_fd_sc_hd__o21ai_0 _1001_ (
    .A1(_0356_),
    .A2(_0687_),
    .B1(_0688_),
    .Y(_0411_)
  );
  sky130_fd_sc_hd__nor3_1 _1002_ (
    .A(_0714_),
    .B(_0517_),
    .C(_0518_),
    .Y(_0689_)
  );
  sky130_fd_sc_hd__xnor2_1 _1003_ (
    .A(_0476_),
    .B(_0689_),
    .Y(_0690_)
  );
  sky130_fd_sc_hd__nand2_1 _1004_ (
    .A(_0454_),
    .B(_0356_),
    .Y(_0691_)
  );
  sky130_fd_sc_hd__o21ai_0 _1005_ (
    .A1(_0356_),
    .A2(_0690_),
    .B1(_0691_),
    .Y(_0412_)
  );
  sky130_fd_sc_hd__xnor2_1 _1006_ (
    .A(_0477_),
    .B(_0520_),
    .Y(_0692_)
  );
  sky130_fd_sc_hd__nor3_1 _1007_ (
    .A(_0714_),
    .B(_0356_),
    .C(_0692_),
    .Y(_0693_)
  );
  sky130_fd_sc_hd__a221o_1 _1008_ (
    .A1(_0455_),
    .A2(_0356_),
    .B1(_0675_),
    .B2(_0477_),
    .C1(_0693_),
    .X(_0413_)
  );
  sky130_fd_sc_hd__xnor2_1 _1009_ (
    .A(_0478_),
    .B(_0521_),
    .Y(_0694_)
  );
  sky130_fd_sc_hd__nor3_1 _1010_ (
    .A(_0714_),
    .B(_0356_),
    .C(_0694_),
    .Y(_0695_)
  );
  sky130_fd_sc_hd__a221o_1 _1011_ (
    .A1(_0456_),
    .A2(_0356_),
    .B1(_0675_),
    .B2(_0478_),
    .C1(_0695_),
    .X(_0414_)
  );
  sky130_fd_sc_hd__xnor2_1 _1012_ (
    .A(_0479_),
    .B(_0522_),
    .Y(_0696_)
  );
  sky130_fd_sc_hd__nor3_1 _1013_ (
    .A(_0714_),
    .B(_0356_),
    .C(_0696_),
    .Y(_0697_)
  );
  sky130_fd_sc_hd__a221o_1 _1014_ (
    .A1(_0457_),
    .A2(_0356_),
    .B1(_0675_),
    .B2(_0479_),
    .C1(_0697_),
    .X(_0415_)
  );
  sky130_fd_sc_hd__xnor2_1 _1015_ (
    .A(_0465_),
    .B(_0523_),
    .Y(_0698_)
  );
  sky130_fd_sc_hd__nor3_1 _1016_ (
    .A(_0714_),
    .B(_0356_),
    .C(_0698_),
    .Y(_0699_)
  );
  sky130_fd_sc_hd__a221o_1 _1017_ (
    .A1(_0443_),
    .A2(_0356_),
    .B1(_0675_),
    .B2(_0465_),
    .C1(_0699_),
    .X(_0416_)
  );
  sky130_fd_sc_hd__xor2_1 _1018_ (
    .A(_0466_),
    .B(_0524_),
    .X(_0700_)
  );
  sky130_fd_sc_hd__nor3_1 _1019_ (
    .A(_0714_),
    .B(_0356_),
    .C(_0700_),
    .Y(_0701_)
  );
  sky130_fd_sc_hd__a221o_1 _1020_ (
    .A1(_0444_),
    .A2(_0356_),
    .B1(_0675_),
    .B2(_0466_),
    .C1(_0701_),
    .X(_0417_)
  );
  sky130_fd_sc_hd__xnor2_1 _1021_ (
    .A(_0467_),
    .B(_0525_),
    .Y(_0702_)
  );
  sky130_fd_sc_hd__nor3_1 _1022_ (
    .A(_0714_),
    .B(_0356_),
    .C(_0702_),
    .Y(_0703_)
  );
  sky130_fd_sc_hd__a221o_1 _1023_ (
    .A1(_0445_),
    .A2(_0356_),
    .B1(_0675_),
    .B2(_0467_),
    .C1(_0703_),
    .X(_0418_)
  );
  sky130_fd_sc_hd__o31ai_1 _1024_ (
    .A1(_0466_),
    .A2(_0467_),
    .A3(_0524_),
    .B1(_0468_),
    .Y(_0704_)
  );
  sky130_fd_sc_hd__a211oi_1 _1025_ (
    .A1(_0526_),
    .A2(_0704_),
    .B1(_0356_),
    .C1(_0714_),
    .Y(_0705_)
  );
  sky130_fd_sc_hd__a221o_1 _1026_ (
    .A1(_0446_),
    .A2(_0356_),
    .B1(_0675_),
    .B2(_0468_),
    .C1(_0705_),
    .X(_0419_)
  );
  sky130_fd_sc_hd__nand2_1 _1027_ (
    .A(_0529_),
    .B(_0676_),
    .Y(_0706_)
  );
  sky130_fd_sc_hd__a21oi_1 _1028_ (
    .A1(_0529_),
    .A2(_0676_),
    .B1(_0469_),
    .Y(_0707_)
  );
  sky130_fd_sc_hd__nor2_1 _1029_ (
    .A(_0526_),
    .B(_0529_),
    .Y(_0708_)
  );
  sky130_fd_sc_hd__a221oi_1 _1030_ (
    .A1(_0514_),
    .A2(_0356_),
    .B1(_0676_),
    .B2(_0708_),
    .C1(_0707_),
    .Y(_0420_)
  );
  sky130_fd_sc_hd__a22o_1 _1031_ (
    .A1(_0448_),
    .A2(_0356_),
    .B1(_0706_),
    .B2(_0470_),
    .X(_0421_)
  );
  sky130_fd_sc_hd__dfrtp_1 _1032_ (
    .CLK(clk),
    .D(_0717_),
    .Q(c_state[0]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1033_ (
    .CLK(clk),
    .D(_0718_),
    .Q(c_state[1]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1034_ (
    .CLK(clk),
    .D(_0719_),
    .Q(c_state[2]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1035_ (
    .CLK(clk),
    .D(_0720_),
    .Q(c_state[3]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1036_ (
    .CLK(clk),
    .D(_0721_),
    .Q(c_state[4]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1037_ (
    .CLK(clk),
    .D(_0722_),
    .Q(c_state[5]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1038_ (
    .CLK(clk),
    .D(_0723_),
    .Q(c_state[6]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1039_ (
    .CLK(clk),
    .D(_0724_),
    .Q(c_state[7]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1040_ (
    .CLK(clk),
    .D(_0725_),
    .Q(c_state[8]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1041_ (
    .CLK(clk),
    .D(_0726_),
    .Q(c_state[9]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1042_ (
    .CLK(clk),
    .D(_0727_),
    .Q(c_state[10]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1043_ (
    .CLK(clk),
    .D(_0728_),
    .Q(c_state[11]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1044_ (
    .CLK(clk),
    .D(_0729_),
    .Q(c_state[12]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1045_ (
    .CLK(clk),
    .D(_0730_),
    .Q(c_state[13]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1046_ (
    .CLK(clk),
    .D(_0731_),
    .Q(c_state[14]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1047_ (
    .CLK(clk),
    .D(_0732_),
    .Q(c_state[15]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1048_ (
    .CLK(clk),
    .D(_0733_),
    .Q(c_state[16]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1049_ (
    .CLK(clk),
    .D(_0004_),
    .Q(cmd_ack),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1050_ (
    .CLK(clk),
    .D(_0734_),
    .Q(scl_oen),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1051_ (
    .CLK(clk),
    .D(_0735_),
    .Q(sda_oen),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1052_ (
    .CLK(clk),
    .D(_0736_),
    .Q(sda_chk),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1053_ (
    .CLK(clk),
    .D(_0000_),
    .Q(al),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__edfxtp_1 _1054_ (
    .CLK(clk),
    .D(sSDA),
    .DE(_0015_),
    .Q(dout)
  );
  sky130_fd_sc_hd__dfrtp_1 _1055_ (
    .CLK(clk),
    .D(_0001_),
    .Q(busy),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1056_ (
    .CLK(clk),
    .D(_0013_),
    .Q(sta_condition),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1057_ (
    .CLK(clk),
    .D(_0014_),
    .Q(sto_condition),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1058_ (
    .CLK(clk),
    .D(_0007_),
    .Q(sSCL),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1059_ (
    .CLK(clk),
    .D(_0008_),
    .Q(sSDA),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1060_ (
    .CLK(clk),
    .D(sSCL),
    .Q(dSCL),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1061_ (
    .CLK(clk),
    .D(sSDA),
    .Q(dSDA),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1062_ (
    .CLK(clk),
    .D(_0737_),
    .Q(cmd_stop),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1063_ (
    .CLK(clk),
    .D(_0738_),
    .Q(fSCL[0]),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1064_ (
    .CLK(clk),
    .D(_0739_),
    .Q(fSCL[1]),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1065_ (
    .CLK(clk),
    .D(_0740_),
    .Q(fSCL[2]),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1066_ (
    .CLK(clk),
    .D(_0006_[0]),
    .Q(filter_cnt[0]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1067_ (
    .CLK(clk),
    .D(_0006_[1]),
    .Q(filter_cnt[1]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1068_ (
    .CLK(clk),
    .D(_0006_[2]),
    .Q(filter_cnt[2]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1069_ (
    .CLK(clk),
    .D(_0006_[3]),
    .Q(filter_cnt[3]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1070_ (
    .CLK(clk),
    .D(_0006_[4]),
    .Q(filter_cnt[4]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1071_ (
    .CLK(clk),
    .D(_0006_[5]),
    .Q(filter_cnt[5]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1072_ (
    .CLK(clk),
    .D(_0006_[6]),
    .Q(filter_cnt[6]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1073_ (
    .CLK(clk),
    .D(_0006_[7]),
    .Q(filter_cnt[7]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1074_ (
    .CLK(clk),
    .D(_0006_[8]),
    .Q(filter_cnt[8]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1075_ (
    .CLK(clk),
    .D(_0006_[9]),
    .Q(filter_cnt[9]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1076_ (
    .CLK(clk),
    .D(_0006_[10]),
    .Q(filter_cnt[10]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1077_ (
    .CLK(clk),
    .D(_0006_[11]),
    .Q(filter_cnt[11]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1078_ (
    .CLK(clk),
    .D(_0006_[12]),
    .Q(filter_cnt[12]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1079_ (
    .CLK(clk),
    .D(_0006_[13]),
    .Q(filter_cnt[13]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1080_ (
    .CLK(clk),
    .D(scl_i),
    .Q(cSCL[0]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1081_ (
    .CLK(clk),
    .D(cSCL[0]),
    .Q(cSCL[1]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1082_ (
    .CLK(clk),
    .D(sda_i),
    .Q(cSDA[0]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1083_ (
    .CLK(clk),
    .D(cSDA[0]),
    .Q(cSDA[1]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1084_ (
    .CLK(clk),
    .D(_0003_),
    .Q(clk_en),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1085_ (
    .CLK(clk),
    .D(_0741_),
    .Q(fSDA[0]),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1086_ (
    .CLK(clk),
    .D(_0742_),
    .Q(fSDA[1]),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfstp_2 _1087_ (
    .CLK(clk),
    .D(_0743_),
    .Q(fSDA[2]),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1088_ (
    .CLK(clk),
    .D(_0012_),
    .Q(slave_wait),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfxtp_1 _1089_ (
    .CLK(clk),
    .D(scl_oen),
    .Q(dscl_oen)
  );
  sky130_fd_sc_hd__dfrtp_1 _1090_ (
    .CLK(clk),
    .D(_0744_),
    .Q(cnt[0]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1091_ (
    .CLK(clk),
    .D(_0745_),
    .Q(cnt[1]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1092_ (
    .CLK(clk),
    .D(_0746_),
    .Q(cnt[2]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1093_ (
    .CLK(clk),
    .D(_0747_),
    .Q(cnt[3]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1094_ (
    .CLK(clk),
    .D(_0748_),
    .Q(cnt[4]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1095_ (
    .CLK(clk),
    .D(_0749_),
    .Q(cnt[5]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1096_ (
    .CLK(clk),
    .D(_0750_),
    .Q(cnt[6]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1097_ (
    .CLK(clk),
    .D(_0751_),
    .Q(cnt[7]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1098_ (
    .CLK(clk),
    .D(_0752_),
    .Q(cnt[8]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1099_ (
    .CLK(clk),
    .D(_0753_),
    .Q(cnt[9]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1100_ (
    .CLK(clk),
    .D(_0754_),
    .Q(cnt[10]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1101_ (
    .CLK(clk),
    .D(_0755_),
    .Q(cnt[11]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1102_ (
    .CLK(clk),
    .D(_0756_),
    .Q(cnt[12]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1103_ (
    .CLK(clk),
    .D(_0757_),
    .Q(cnt[13]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1104_ (
    .CLK(clk),
    .D(_0758_),
    .Q(cnt[14]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _1105_ (
    .CLK(clk),
    .D(_0759_),
    .Q(cnt[15]),
    .RESET_B(nReset)
  );
  assign _0002_[17] = 1'h0;
  assign { _0760_[15:13], _0760_[11:10], _0760_[8], _0760_[6:3], _0760_[1:0] } = 12'h000;
  assign c_state[17] = 1'h0;
  assign scl_o = 1'h0;
  assign sda_o = 1'h0;
  assign _0378_ = al;
  assign _0458_ = clk_en;
  assign _0432_ = c_state[16];
  assign _0433_ = c_state[1];
  assign _0425_ = c_state[0];
  assign _0435_ = c_state[3];
  assign _0434_ = c_state[2];
  assign _0437_ = c_state[5];
  assign _0436_ = c_state[4];
  assign _0438_ = c_state[6];
  assign _0439_ = c_state[7];
  assign _0441_ = c_state[9];
  assign _0440_ = c_state[8];
  assign _0427_ = c_state[11];
  assign _0426_ = c_state[10];
  assign _0428_ = c_state[12];
  assign _0429_ = c_state[13];
  assign _0431_ = c_state[15];
  assign _0430_ = c_state[14];
  assign _0496_ = filter_cnt[1];
  assign _0491_ = filter_cnt[0];
  assign _0498_ = filter_cnt[3];
  assign _0497_ = filter_cnt[2];
  assign _0500_ = filter_cnt[5];
  assign _0499_ = filter_cnt[4];
  assign _0502_ = filter_cnt[7];
  assign _0501_ = filter_cnt[6];
  assign _0504_ = filter_cnt[9];
  assign _0503_ = filter_cnt[8];
  assign _0493_ = filter_cnt[11];
  assign _0492_ = filter_cnt[10];
  assign _0495_ = filter_cnt[13];
  assign _0494_ = filter_cnt[12];
  assign _0471_ = cnt[1];
  assign _0464_ = cnt[0];
  assign _0473_ = cnt[3];
  assign _0472_ = cnt[2];
  assign _0475_ = cnt[5];
  assign _0474_ = cnt[4];
  assign _0477_ = cnt[7];
  assign _0476_ = cnt[6];
  assign _0479_ = cnt[9];
  assign _0478_ = cnt[8];
  assign _0466_ = cnt[11];
  assign _0465_ = cnt[10];
  assign _0468_ = cnt[13];
  assign _0467_ = cnt[12];
  assign _0470_ = cnt[15];
  assign _0469_ = cnt[14];
  assign _0484_ = ena;
  assign _0709_ = sSCL;
  assign _0480_ = dSCL;
  assign _0711_ = scl_oen;
  assign _0003_ = _0356_;
  assign _0714_ = slave_wait;
  assign _0459_ = cmd[0];
  assign _0460_ = cmd[1];
  assign _0462_ = cmd[3];
  assign _0461_ = cmd[2];
  assign _0004_ = _0357_;
  assign _0450_ = clk_cnt[2];
  assign _0006_[0] = _0358_;
  assign _0451_ = clk_cnt[3];
  assign _0006_[1] = _0363_;
  assign _0452_ = clk_cnt[4];
  assign _0006_[2] = _0364_;
  assign _0453_ = clk_cnt[5];
  assign _0006_[3] = _0365_;
  assign _0454_ = clk_cnt[6];
  assign _0006_[4] = _0366_;
  assign _0455_ = clk_cnt[7];
  assign _0006_[5] = _0367_;
  assign _0456_ = clk_cnt[8];
  assign _0006_[6] = _0368_;
  assign _0457_ = clk_cnt[9];
  assign _0006_[7] = _0369_;
  assign _0443_ = clk_cnt[10];
  assign _0006_[8] = _0370_;
  assign _0444_ = clk_cnt[11];
  assign _0006_[9] = _0371_;
  assign _0445_ = clk_cnt[12];
  assign _0006_[10] = _0359_;
  assign _0446_ = clk_cnt[13];
  assign _0006_[11] = _0360_;
  assign _0447_ = clk_cnt[14];
  assign _0006_[12] = _0361_;
  assign _0448_ = clk_cnt[15];
  assign _0006_[13] = _0362_;
  assign _0442_ = clk_cnt[0];
  assign _0449_ = clk_cnt[1];
  assign _0483_ = dscl_oen;
  assign _0012_ = _0374_;
  assign _0487_ = fSCL[2];
  assign _0486_ = fSCL[1];
  assign _0485_ = fSCL[0];
  assign _0007_ = _0372_;
  assign _0490_ = fSDA[2];
  assign _0489_ = fSDA[1];
  assign _0488_ = fSDA[0];
  assign _0008_ = _0373_;
  assign _0710_ = sSDA;
  assign _0481_ = dSDA;
  assign _0013_ = _0375_;
  assign _0014_ = _0376_;
  assign _0422_ = busy;
  assign _0715_ = sta_condition;
  assign _0716_ = sto_condition;
  assign _0001_ = _0355_;
  assign _0712_ = sda_chk;
  assign _0713_ = sda_oen;
  assign _0463_ = cmd_stop;
  assign _0000_ = _0354_;
  assign _0015_ = _0377_;
  assign _0482_ = din;
  assign _0717_ = _0379_;
  assign _0718_ = _0380_;
  assign _0719_ = _0381_;
  assign _0720_ = _0382_;
  assign _0721_ = _0383_;
  assign _0722_ = _0384_;
  assign _0723_ = _0385_;
  assign _0724_ = _0386_;
  assign _0725_ = _0387_;
  assign _0726_ = _0388_;
  assign _0727_ = _0389_;
  assign _0728_ = _0390_;
  assign _0729_ = _0391_;
  assign _0730_ = _0392_;
  assign _0731_ = _0393_;
  assign _0732_ = _0394_;
  assign _0733_ = _0395_;
  assign _0734_ = _0396_;
  assign _0735_ = _0397_;
  assign _0736_ = _0398_;
  assign _0737_ = _0399_;
  assign _0423_ = cSCL[1];
  assign _0738_ = _0400_;
  assign _0739_ = _0401_;
  assign _0740_ = _0402_;
  assign _0424_ = cSDA[1];
  assign _0741_ = _0403_;
  assign _0742_ = _0404_;
  assign _0743_ = _0405_;
  assign _0744_ = _0406_;
  assign _0745_ = _0407_;
  assign _0746_ = _0408_;
  assign _0747_ = _0409_;
  assign _0748_ = _0410_;
  assign _0749_ = _0411_;
  assign _0750_ = _0412_;
  assign _0751_ = _0413_;
  assign _0752_ = _0414_;
  assign _0753_ = _0415_;
  assign _0754_ = _0416_;
  assign _0755_ = _0417_;
  assign _0756_ = _0418_;
  assign _0757_ = _0419_;
  assign _0758_ = _0420_;
  assign _0759_ = _0421_;
endmodule

module i2c_master_byte_ctrl(clk, nReset, ena, clk_cnt, start, stop, read, write, ack_in, din, cmd_ack, ack_out, dout, i2c_busy, i2c_al, scl_i, scl_o, scl_oen, sda_i, sda_o, sda_oen
);
  wire _000_;
  wire _001_;
  wire [3:0] _002_;
  wire _003_;
  wire [2:0] _004_;
  wire _005_;
  wire _006_;
  wire [7:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  input ack_in;
  wire ack_in;
  output ack_out;
  wire ack_out;
  wire [5:0] c_state;
  input clk;
  wire clk;
  input [15:0] clk_cnt;
  wire [15:0] clk_cnt;
  output cmd_ack;
  wire cmd_ack;
  wire core_ack;
  wire [3:0] core_cmd;
  wire core_rxd;
  wire core_txd;
  wire [2:0] dcnt;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  wire [7:0] dout;
  input ena;
  wire ena;
  output i2c_al;
  wire i2c_al;
  output i2c_busy;
  wire i2c_busy;
  wire ld;
  input nReset;
  wire nReset;
  input read;
  wire read;
  input scl_i;
  wire scl_i;
  output scl_o;
  wire scl_o;
  output scl_oen;
  wire scl_oen;
  input sda_i;
  wire sda_i;
  output sda_o;
  wire sda_o;
  output sda_oen;
  wire sda_oen;
  wire shift;
  wire [7:0] sr;
  input start;
  wire start;
  input stop;
  wire stop;
  input write;
  wire write;
  sky130_fd_sc_hd__clkinv_1 _302_ (
    .A(_169_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__clkinv_1 _303_ (
    .A(_173_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__clkinv_1 _304_ (
    .A(_171_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__clkinv_1 _305_ (
    .A(_192_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__clkinv_1 _306_ (
    .A(_274_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__clkinv_1 _307_ (
    .A(_282_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__clkinv_1 _308_ (
    .A(_189_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__clkinv_1 _309_ (
    .A(_281_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nor3_1 _310_ (
    .A(_283_),
    .B(_273_),
    .C(_285_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nor3_1 _311_ (
    .A(_284_),
    .B(_273_),
    .C(_285_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__or3_1 _312_ (
    .A(_284_),
    .B(_273_),
    .C(_285_),
    .X(_254_)
  );
  sky130_fd_sc_hd__and3_1 _313_ (
    .A(_245_),
    .B(_167_),
    .C(_254_),
    .X(_255_)
  );
  sky130_fd_sc_hd__nand3_1 _314_ (
    .A(_245_),
    .B(_167_),
    .C(_254_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nor2_1 _315_ (
    .A(_191_),
    .B(_256_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _316_ (
    .A(_174_),
    .SLEEP(_191_),
    .X(_258_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(_174_),
    .B(_191_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(_168_),
    .B(_259_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__a32oi_1 _319_ (
    .A1(_284_),
    .A2(_169_),
    .A3(_258_),
    .B1(_257_),
    .B2(_252_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(_260_),
    .B(_261_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o21ai_0 _321_ (
    .A1(_173_),
    .A2(_253_),
    .B1(_167_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(_174_),
    .B(_169_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2_1 _323_ (
    .A(_284_),
    .B(_263_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__a21oi_1 _324_ (
    .A1(_168_),
    .A2(_258_),
    .B1(_264_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__nand3b_1 _325_ (
    .A_N(_191_),
    .B(_262_),
    .C(_265_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor2_1 _326_ (
    .A(_191_),
    .B(_283_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nand3b_1 _327_ (
    .A_N(_273_),
    .B(_285_),
    .C(_266_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__nor3_1 _328_ (
    .A(_180_),
    .B(_181_),
    .C(_182_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _329_ (
    .A(_258_),
    .SLEEP(_268_),
    .X(_269_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _330_ (
    .A(_172_),
    .SLEEP(_273_),
    .X(_270_)
  );
  sky130_fd_sc_hd__a22o_1 _331_ (
    .A1(_170_),
    .A2(_259_),
    .B1(_270_),
    .B2(_258_),
    .X(_271_)
  );
  sky130_fd_sc_hd__a21oi_1 _332_ (
    .A1(_170_),
    .A2(_269_),
    .B1(_271_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__o21ai_0 _333_ (
    .A1(_256_),
    .A2(_267_),
    .B1(_272_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand3_1 _334_ (
    .A(_273_),
    .B(_255_),
    .C(_266_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(_171_),
    .B(_269_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__a32oi_1 _336_ (
    .A1(_273_),
    .A2(_172_),
    .A3(_258_),
    .B1(_259_),
    .B2(_171_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nand3_1 _337_ (
    .A(_193_),
    .B(_194_),
    .C(_195_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(_172_),
    .B(_259_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nand2b_1 _339_ (
    .A_N(_191_),
    .B(_283_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o21ai_0 _340_ (
    .A1(_256_),
    .A2(_197_),
    .B1(_196_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _341_ (
    .A(_170_),
    .SLEEP(_171_),
    .X(_198_)
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(_258_),
    .B(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__a32o_1 _343_ (
    .A1(_258_),
    .A2(_268_),
    .A3(_198_),
    .B1(_259_),
    .B2(_169_),
    .X(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _344_ (
    .A1(_246_),
    .A2(_268_),
    .B1(_199_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(_174_),
    .B(_171_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(_282_),
    .B(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__a21oi_1 _347_ (
    .A1(_169_),
    .A2(_246_),
    .B1(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(_244_),
    .B(_200_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__a21oi_1 _349_ (
    .A1(_149_),
    .A2(_203_),
    .B1(_202_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__a21oi_1 _350_ (
    .A1(_263_),
    .A2(_204_),
    .B1(_191_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _351_ (
    .A(_191_),
    .B(_265_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21o_1 _352_ (
    .A1(_172_),
    .A2(_258_),
    .B1(_257_),
    .X(_141_)
  );
  sky130_fd_sc_hd__nand3_1 _353_ (
    .A(_174_),
    .B(_169_),
    .C(_179_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nand2_1 _354_ (
    .A(_150_),
    .B(_263_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__a21oi_1 _355_ (
    .A1(_205_),
    .A2(_206_),
    .B1(_191_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor4_1 _356_ (
    .A(_168_),
    .B(_169_),
    .C(_172_),
    .D(_198_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__o21bai_1 _357_ (
    .A1(_167_),
    .A2(_207_),
    .B1_N(_191_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o21ai_0 _358_ (
    .A1(_168_),
    .A2(_170_),
    .B1(_259_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__o31ai_1 _359_ (
    .A1(_169_),
    .A2(_172_),
    .A3(_171_),
    .B1(_259_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o211ai_1 _360_ (
    .A1(_255_),
    .A2(_208_),
    .B1(_209_),
    .C1(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nor2b_1 _361_ (
    .A(_197_),
    .B_N(_207_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__mux2_1 _362_ (
    .A0(_212_),
    .A1(_175_),
    .S(_211_),
    .X(_152_)
  );
  sky130_fd_sc_hd__a22oi_1 _363_ (
    .A1(_284_),
    .A2(_169_),
    .B1(_252_),
    .B2(_207_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor2_1 _364_ (
    .A(_191_),
    .B(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__mux2_1 _365_ (
    .A0(_214_),
    .A1(_176_),
    .S(_211_),
    .X(_153_)
  );
  sky130_fd_sc_hd__o21ai_0 _366_ (
    .A1(_191_),
    .A2(_207_),
    .B1(_267_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nor2_1 _367_ (
    .A(_170_),
    .B(_268_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__a21oi_1 _368_ (
    .A1(_246_),
    .A2(_268_),
    .B1(_216_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__o31a_1 _369_ (
    .A1(_270_),
    .A2(_207_),
    .A3(_217_),
    .B1(_215_),
    .X(_218_)
  );
  sky130_fd_sc_hd__mux2_1 _370_ (
    .A0(_218_),
    .A1(_177_),
    .S(_211_),
    .X(_154_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _371_ (
    .A1_N(_191_),
    .A2_N(_207_),
    .B1(_266_),
    .B2(_273_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__mux2i_1 _372_ (
    .A0(_171_),
    .A1(_170_),
    .S(_268_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__a21oi_1 _373_ (
    .A1(_273_),
    .A2(_172_),
    .B1(_207_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__a21oi_1 _374_ (
    .A1(_220_),
    .A2(_221_),
    .B1(_219_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__mux2_1 _375_ (
    .A0(_222_),
    .A1(_178_),
    .S(_211_),
    .X(_155_)
  );
  sky130_fd_sc_hd__nand2b_1 _376_ (
    .A_N(_180_),
    .B(_274_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__a21oi_1 _377_ (
    .A1(_180_),
    .A2(_248_),
    .B1(_192_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nand2_1 _378_ (
    .A(_223_),
    .B(_224_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _379_ (
    .A(_181_),
    .SLEEP(_223_),
    .X(_225_)
  );
  sky130_fd_sc_hd__a21oi_1 _380_ (
    .A1(_181_),
    .A2(_223_),
    .B1(_192_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__nand2_1 _381_ (
    .A(_225_),
    .B(_226_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a21oi_1 _382_ (
    .A1(_182_),
    .A2(_225_),
    .B1(_192_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__o21ai_0 _383_ (
    .A1(_182_),
    .A2(_225_),
    .B1(_227_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand2_1 _384_ (
    .A(_247_),
    .B(_274_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor2_1 _385_ (
    .A(_179_),
    .B(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nand2_1 _386_ (
    .A(_247_),
    .B(_248_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__o22ai_1 _387_ (
    .A1(_247_),
    .A2(_183_),
    .B1(_275_),
    .B2(_230_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nor2_1 _388_ (
    .A(_229_),
    .B(_231_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nor2_1 _389_ (
    .A(_275_),
    .B(_228_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__o22ai_1 _390_ (
    .A1(_247_),
    .A2(_184_),
    .B1(_276_),
    .B2(_230_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nor2_1 _391_ (
    .A(_232_),
    .B(_233_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nor2_1 _392_ (
    .A(_276_),
    .B(_228_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__o22ai_1 _393_ (
    .A1(_247_),
    .A2(_185_),
    .B1(_277_),
    .B2(_230_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nor2_1 _394_ (
    .A(_234_),
    .B(_235_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nor2_1 _395_ (
    .A(_277_),
    .B(_228_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__o22ai_1 _396_ (
    .A1(_247_),
    .A2(_186_),
    .B1(_278_),
    .B2(_230_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor2_1 _397_ (
    .A(_236_),
    .B(_237_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2_1 _398_ (
    .A(_279_),
    .B(_230_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__o22ai_1 _399_ (
    .A1(_247_),
    .A2(_187_),
    .B1(_228_),
    .B2(_278_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nor2_1 _400_ (
    .A(_238_),
    .B(_239_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nor2_1 _401_ (
    .A(_279_),
    .B(_228_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__o22ai_1 _402_ (
    .A1(_247_),
    .A2(_188_),
    .B1(_280_),
    .B2(_230_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nor2_1 _403_ (
    .A(_240_),
    .B(_241_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__o22ai_1 _404_ (
    .A1(_280_),
    .A2(_228_),
    .B1(_230_),
    .B2(_281_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__a21oi_1 _405_ (
    .A1(_192_),
    .A2(_250_),
    .B1(_242_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(_192_),
    .B(_190_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__o221ai_1 _407_ (
    .A1(_251_),
    .A2(_228_),
    .B1(_230_),
    .B2(_249_),
    .C1(_243_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__dfstp_2 _408_ (
    .CLK(clk),
    .D(_008_),
    .Q(c_state[0]),
    .SET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _409_ (
    .CLK(clk),
    .D(_009_),
    .Q(c_state[1]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _410_ (
    .CLK(clk),
    .D(_010_),
    .Q(c_state[2]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _411_ (
    .CLK(clk),
    .D(_011_),
    .Q(c_state[3]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _412_ (
    .CLK(clk),
    .D(_012_),
    .Q(c_state[4]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _413_ (
    .CLK(clk),
    .D(_013_),
    .Q(c_state[5]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _414_ (
    .CLK(clk),
    .D(_001_),
    .Q(cmd_ack),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _415_ (
    .CLK(clk),
    .D(_286_),
    .Q(ack_out),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _416_ (
    .CLK(clk),
    .D(_003_),
    .Q(core_txd),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _417_ (
    .CLK(clk),
    .D(_006_),
    .Q(shift),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _418_ (
    .CLK(clk),
    .D(_005_),
    .Q(ld),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _419_ (
    .CLK(clk),
    .D(_287_),
    .Q(core_cmd[0]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _420_ (
    .CLK(clk),
    .D(_288_),
    .Q(core_cmd[1]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _421_ (
    .CLK(clk),
    .D(_289_),
    .Q(core_cmd[2]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _422_ (
    .CLK(clk),
    .D(_290_),
    .Q(core_cmd[3]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _423_ (
    .CLK(clk),
    .D(_291_),
    .Q(dcnt[0]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _424_ (
    .CLK(clk),
    .D(_292_),
    .Q(dcnt[1]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _425_ (
    .CLK(clk),
    .D(_293_),
    .Q(dcnt[2]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _426_ (
    .CLK(clk),
    .D(_294_),
    .Q(sr[0]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _427_ (
    .CLK(clk),
    .D(_295_),
    .Q(sr[1]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _428_ (
    .CLK(clk),
    .D(_296_),
    .Q(sr[2]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _429_ (
    .CLK(clk),
    .D(_297_),
    .Q(sr[3]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _430_ (
    .CLK(clk),
    .D(_298_),
    .Q(sr[4]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _431_ (
    .CLK(clk),
    .D(_299_),
    .Q(sr[5]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _432_ (
    .CLK(clk),
    .D(_300_),
    .Q(sr[6]),
    .RESET_B(nReset)
  );
  sky130_fd_sc_hd__dfrtp_1 _433_ (
    .CLK(clk),
    .D(_301_),
    .Q(sr[7]),
    .RESET_B(nReset)
  );
  i2c_master_bit_ctrl bit_controller (
    .al(i2c_al),
    .busy(i2c_busy),
    .clk(clk),
    .clk_cnt(clk_cnt),
    .cmd(core_cmd),
    .cmd_ack(core_ack),
    .din(core_txd),
    .dout(core_rxd),
    .ena(ena),
    .nReset(nReset),
    .scl_i(scl_i),
    .scl_o(scl_o),
    .scl_oen(scl_oen),
    .sda_i(sda_i),
    .sda_o(sda_o),
    .sda_oen(sda_oen)
  );
  assign dout = sr;
  assign _168_ = c_state[1];
  assign _174_ = core_ack;
  assign _191_ = i2c_al;
  assign _284_ = stop;
  assign _169_ = c_state[2];
  assign _283_ = start;
  assign _273_ = read;
  assign _285_ = write;
  assign _173_ = cmd_ack;
  assign _167_ = c_state[0];
  assign _009_ = _144_;
  assign _008_ = _143_;
  assign _170_ = c_state[3];
  assign _172_ = c_state[5];
  assign _180_ = dcnt[0];
  assign _181_ = dcnt[1];
  assign _182_ = dcnt[2];
  assign _011_ = _146_;
  assign _171_ = c_state[4];
  assign _012_ = _147_;
  assign _013_ = _148_;
  assign _192_ = ld;
  assign _274_ = shift;
  assign _010_ = _145_;
  assign _006_ = _142_;
  assign _149_ = ack_in;
  assign _282_ = sr[7];
  assign _003_ = _140_;
  assign _179_ = core_rxd;
  assign _183_ = din[0];
  assign _275_ = sr[0];
  assign _184_ = din[1];
  assign _276_ = sr[1];
  assign _185_ = din[2];
  assign _277_ = sr[2];
  assign _186_ = din[3];
  assign _278_ = sr[3];
  assign _187_ = din[4];
  assign _279_ = sr[4];
  assign _188_ = din[5];
  assign _280_ = sr[5];
  assign _189_ = din[6];
  assign _281_ = sr[6];
  assign _190_ = din[7];
  assign _001_ = _139_;
  assign _005_ = _141_;
  assign _150_ = ack_out;
  assign _286_ = _151_;
  assign _175_ = core_cmd[0];
  assign _287_ = _152_;
  assign _176_ = core_cmd[1];
  assign _288_ = _153_;
  assign _177_ = core_cmd[2];
  assign _289_ = _154_;
  assign _178_ = core_cmd[3];
  assign _290_ = _155_;
  assign _291_ = _156_;
  assign _292_ = _157_;
  assign _293_ = _158_;
  assign _294_ = _159_;
  assign _295_ = _160_;
  assign _296_ = _161_;
  assign _297_ = _162_;
  assign _298_ = _163_;
  assign _299_ = _164_;
  assign _300_ = _165_;
  assign _301_ = _166_;
endmodule
